// Package prowlarr provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package prowlarr

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

const (
	X_Api_KeyScopes = "X_Api_Key.Scopes"
	ApikeyScopes    = "apikey.Scopes"
)

// Defines values for ApplicationSyncLevel.
const (
	ApplicationSyncLevelAddOnly  ApplicationSyncLevel = "addOnly"
	ApplicationSyncLevelDisabled ApplicationSyncLevel = "disabled"
	ApplicationSyncLevelFullSync ApplicationSyncLevel = "fullSync"
)

// Defines values for AuthenticationRequiredType.
const (
	DisabledForLocalAddresses AuthenticationRequiredType = "disabledForLocalAddresses"
	Enabled                   AuthenticationRequiredType = "enabled"
)

// Defines values for AuthenticationType.
const (
	AuthenticationTypeBasic    AuthenticationType = "basic"
	AuthenticationTypeExternal AuthenticationType = "external"
	AuthenticationTypeForms    AuthenticationType = "forms"
	AuthenticationTypeNone     AuthenticationType = "none"
)

// Defines values for BackupType.
const (
	BackupTypeManual    BackupType = "manual"
	BackupTypeScheduled BackupType = "scheduled"
	BackupTypeUpdate    BackupType = "update"
)

// Defines values for BookSearchParam.
const (
	BookSearchParamAuthor    BookSearchParam = "author"
	BookSearchParamGenre     BookSearchParam = "genre"
	BookSearchParamPublisher BookSearchParam = "publisher"
	BookSearchParamQ         BookSearchParam = "q"
	BookSearchParamTitle     BookSearchParam = "title"
	BookSearchParamYear      BookSearchParam = "year"
)

// Defines values for CertificateValidationType.
const (
	CertificateValidationTypeDisabled                  CertificateValidationType = "disabled"
	CertificateValidationTypeDisabledForLocalAddresses CertificateValidationType = "disabledForLocalAddresses"
	CertificateValidationTypeEnabled                   CertificateValidationType = "enabled"
)

// Defines values for CommandPriority.
const (
	CommandPriorityHigh   CommandPriority = "high"
	CommandPriorityLow    CommandPriority = "low"
	CommandPriorityNormal CommandPriority = "normal"
)

// Defines values for CommandStatus.
const (
	Aborted   CommandStatus = "aborted"
	Cancelled CommandStatus = "cancelled"
	Completed CommandStatus = "completed"
	Failed    CommandStatus = "failed"
	Orphaned  CommandStatus = "orphaned"
	Queued    CommandStatus = "queued"
	Started   CommandStatus = "started"
)

// Defines values for CommandTrigger.
const (
	CommandTriggerManual      CommandTrigger = "manual"
	CommandTriggerScheduled   CommandTrigger = "scheduled"
	CommandTriggerUnspecified CommandTrigger = "unspecified"
)

// Defines values for DownloadProtocol.
const (
	Torrent DownloadProtocol = "torrent"
	Unknown DownloadProtocol = "unknown"
	Usenet  DownloadProtocol = "usenet"
)

// Defines values for IndexerPrivacy.
const (
	Private     IndexerPrivacy = "private"
	Public      IndexerPrivacy = "public"
	SemiPrivate IndexerPrivacy = "semiPrivate"
)

// Defines values for MovieSearchParam.
const (
	MovieSearchParamDoubanId  MovieSearchParam = "doubanId"
	MovieSearchParamGenre     MovieSearchParam = "genre"
	MovieSearchParamImdbId    MovieSearchParam = "imdbId"
	MovieSearchParamImdbTitle MovieSearchParam = "imdbTitle"
	MovieSearchParamImdbYear  MovieSearchParam = "imdbYear"
	MovieSearchParamQ         MovieSearchParam = "q"
	MovieSearchParamTmdbId    MovieSearchParam = "tmdbId"
	MovieSearchParamTraktId   MovieSearchParam = "traktId"
	MovieSearchParamYear      MovieSearchParam = "year"
)

// Defines values for MusicSearchParam.
const (
	MusicSearchParamAlbum  MusicSearchParam = "album"
	MusicSearchParamArtist MusicSearchParam = "artist"
	MusicSearchParamGenre  MusicSearchParam = "genre"
	MusicSearchParamLabel  MusicSearchParam = "label"
	MusicSearchParamQ      MusicSearchParam = "q"
	MusicSearchParamTrack  MusicSearchParam = "track"
	MusicSearchParamYear   MusicSearchParam = "year"
)

// Defines values for PrivacyLevel.
const (
	PrivacyLevelApiKey   PrivacyLevel = "apiKey"
	PrivacyLevelNormal   PrivacyLevel = "normal"
	PrivacyLevelPassword PrivacyLevel = "password"
	PrivacyLevelUserName PrivacyLevel = "userName"
)

// Defines values for ProviderMessageType.
const (
	Error   ProviderMessageType = "error"
	Info    ProviderMessageType = "info"
	Warning ProviderMessageType = "warning"
)

// Defines values for ProxyType.
const (
	Http   ProxyType = "http"
	Socks4 ProxyType = "socks4"
	Socks5 ProxyType = "socks5"
)

// Defines values for SearchParam.
const (
	SearchParamQ SearchParam = "q"
)

// Defines values for TvSearchParam.
const (
	DoubanId TvSearchParam = "doubanId"
	Ep       TvSearchParam = "ep"
	Genre    TvSearchParam = "genre"
	ImdbId   TvSearchParam = "imdbId"
	Q        TvSearchParam = "q"
	RId      TvSearchParam = "rId"
	Season   TvSearchParam = "season"
	TmdbId   TvSearchParam = "tmdbId"
	TraktId  TvSearchParam = "traktId"
	TvMazeId TvSearchParam = "tvMazeId"
	TvdbId   TvSearchParam = "tvdbId"
	Year     TvSearchParam = "year"
)

// Defines values for UpdateMechanism.
const (
	UpdateMechanismApt      UpdateMechanism = "apt"
	UpdateMechanismBuiltIn  UpdateMechanism = "builtIn"
	UpdateMechanismDocker   UpdateMechanism = "docker"
	UpdateMechanismExternal UpdateMechanism = "external"
	UpdateMechanismScript   UpdateMechanism = "script"
)

// ApplicationResource defines model for ApplicationResource.
type ApplicationResource struct {
	ConfigContract     *string                `json:"configContract"`
	Fields             *[]Field               `json:"fields"`
	Id                 *int32                 `json:"id,omitempty"`
	Implementation     *string                `json:"implementation"`
	ImplementationName *string                `json:"implementationName"`
	InfoLink           *string                `json:"infoLink"`
	Message            *ProviderMessage       `json:"message,omitempty"`
	Name               *string                `json:"name"`
	Presets            *[]ApplicationResource `json:"presets"`
	SyncLevel          *ApplicationSyncLevel  `json:"syncLevel,omitempty"`
	Tags               *[]int32               `json:"tags"`
	TestCommand        *string                `json:"testCommand"`
}

// ApplicationSyncLevel defines model for ApplicationSyncLevel.
type ApplicationSyncLevel string

// AuthenticationRequiredType defines model for AuthenticationRequiredType.
type AuthenticationRequiredType string

// AuthenticationType defines model for AuthenticationType.
type AuthenticationType string

// BackupResource defines model for BackupResource.
type BackupResource struct {
	Id   *int32      `json:"id,omitempty"`
	Name *string     `json:"name"`
	Path *string     `json:"path"`
	Size *int64      `json:"size,omitempty"`
	Time *time.Time  `json:"time,omitempty"`
	Type *BackupType `json:"type,omitempty"`
}

// BackupType defines model for BackupType.
type BackupType string

// BookSearchParam defines model for BookSearchParam.
type BookSearchParam string

// CertificateValidationType defines model for CertificateValidationType.
type CertificateValidationType string

// Command defines model for Command.
type Command struct {
	ClientUserAgent     *string         `json:"clientUserAgent"`
	CompletionMessage   *string         `json:"completionMessage"`
	IsExclusive         *bool           `json:"isExclusive,omitempty"`
	IsTypeExclusive     *bool           `json:"isTypeExclusive,omitempty"`
	LastExecutionTime   *time.Time      `json:"lastExecutionTime"`
	LastStartTime       *time.Time      `json:"lastStartTime"`
	Name                *string         `json:"name"`
	RequiresDiskAccess  *bool           `json:"requiresDiskAccess,omitempty"`
	SendUpdatesToClient *bool           `json:"sendUpdatesToClient,omitempty"`
	SuppressMessages    *bool           `json:"suppressMessages,omitempty"`
	Trigger             *CommandTrigger `json:"trigger,omitempty"`
	UpdateScheduledTask *bool           `json:"updateScheduledTask,omitempty"`
}

// CommandPriority defines model for CommandPriority.
type CommandPriority string

// CommandResource defines model for CommandResource.
type CommandResource struct {
	Body                *Command         `json:"body,omitempty"`
	ClientUserAgent     *string          `json:"clientUserAgent"`
	CommandName         *string          `json:"commandName"`
	Duration            *string          `json:"duration"`
	Ended               *time.Time       `json:"ended"`
	Exception           *string          `json:"exception"`
	Id                  *int32           `json:"id,omitempty"`
	LastExecutionTime   *time.Time       `json:"lastExecutionTime"`
	Message             *string          `json:"message"`
	Name                *string          `json:"name"`
	Priority            *CommandPriority `json:"priority,omitempty"`
	Queued              *time.Time       `json:"queued,omitempty"`
	SendUpdatesToClient *bool            `json:"sendUpdatesToClient,omitempty"`
	Started             *time.Time       `json:"started"`
	StateChangeTime     *time.Time       `json:"stateChangeTime"`
	Status              *CommandStatus   `json:"status,omitempty"`
	Trigger             *CommandTrigger  `json:"trigger,omitempty"`
	UpdateScheduledTask *bool            `json:"updateScheduledTask,omitempty"`
}

// CommandStatus defines model for CommandStatus.
type CommandStatus string

// CommandTrigger defines model for CommandTrigger.
type CommandTrigger string

// DownloadClientCategory defines model for DownloadClientCategory.
type DownloadClientCategory struct {
	Categories     *[]int32 `json:"categories"`
	ClientCategory *string  `json:"clientCategory"`
}

// DownloadClientResource defines model for DownloadClientResource.
type DownloadClientResource struct {
	Categories         *[]DownloadClientCategory `json:"categories"`
	ConfigContract     *string                   `json:"configContract"`
	Enable             *bool                     `json:"enable,omitempty"`
	Fields             *[]Field                  `json:"fields"`
	Id                 *int32                    `json:"id,omitempty"`
	Implementation     *string                   `json:"implementation"`
	ImplementationName *string                   `json:"implementationName"`
	InfoLink           *string                   `json:"infoLink"`
	Message            *ProviderMessage          `json:"message,omitempty"`
	Name               *string                   `json:"name"`
	Presets            *[]DownloadClientResource `json:"presets"`
	Priority           *int32                    `json:"priority,omitempty"`
	Protocol           *DownloadProtocol         `json:"protocol,omitempty"`
	SupportsCategories *bool                     `json:"supportsCategories,omitempty"`
	Tags               *[]int32                  `json:"tags"`
}

// DownloadProtocol defines model for DownloadProtocol.
type DownloadProtocol string

// Field defines model for Field.
type Field struct {
	Advanced                    *bool           `json:"advanced,omitempty"`
	HelpLink                    *string         `json:"helpLink"`
	HelpText                    *string         `json:"helpText"`
	HelpTextWarning             *string         `json:"helpTextWarning"`
	Hidden                      *string         `json:"hidden"`
	IsFloat                     *bool           `json:"isFloat,omitempty"`
	Label                       *string         `json:"label"`
	Name                        *string         `json:"name"`
	Order                       *int32          `json:"order,omitempty"`
	Placeholder                 *string         `json:"placeholder"`
	Privacy                     *PrivacyLevel   `json:"privacy,omitempty"`
	Section                     *string         `json:"section"`
	SelectOptions               *[]SelectOption `json:"selectOptions"`
	SelectOptionsProviderAction *string         `json:"selectOptionsProviderAction"`
	Type                        *string         `json:"type"`
	Unit                        *string         `json:"unit"`
	Value                       interface{}     `json:"value"`
}

// HostConfigResource defines model for HostConfigResource.
type HostConfigResource struct {
	AnalyticsEnabled          *bool                       `json:"analyticsEnabled,omitempty"`
	ApiKey                    *string                     `json:"apiKey"`
	ApplicationUrl            *string                     `json:"applicationUrl"`
	AuthenticationMethod      *AuthenticationType         `json:"authenticationMethod,omitempty"`
	AuthenticationRequired    *AuthenticationRequiredType `json:"authenticationRequired,omitempty"`
	BackupFolder              *string                     `json:"backupFolder"`
	BackupInterval            *int32                      `json:"backupInterval,omitempty"`
	BackupRetention           *int32                      `json:"backupRetention,omitempty"`
	BindAddress               *string                     `json:"bindAddress"`
	Branch                    *string                     `json:"branch"`
	CertificateValidation     *CertificateValidationType  `json:"certificateValidation,omitempty"`
	ConsoleLogLevel           *string                     `json:"consoleLogLevel"`
	EnableSsl                 *bool                       `json:"enableSsl,omitempty"`
	HistoryCleanupDays        *int32                      `json:"historyCleanupDays,omitempty"`
	Id                        *int32                      `json:"id,omitempty"`
	InstanceName              *string                     `json:"instanceName"`
	LaunchBrowser             *bool                       `json:"launchBrowser,omitempty"`
	LogLevel                  *string                     `json:"logLevel"`
	LogSizeLimit              *int32                      `json:"logSizeLimit,omitempty"`
	Password                  *string                     `json:"password"`
	PasswordConfirmation      *string                     `json:"passwordConfirmation"`
	Port                      *int32                      `json:"port,omitempty"`
	ProxyBypassFilter         *string                     `json:"proxyBypassFilter"`
	ProxyBypassLocalAddresses *bool                       `json:"proxyBypassLocalAddresses,omitempty"`
	ProxyEnabled              *bool                       `json:"proxyEnabled,omitempty"`
	ProxyHostname             *string                     `json:"proxyHostname"`
	ProxyPassword             *string                     `json:"proxyPassword"`
	ProxyPort                 *int32                      `json:"proxyPort,omitempty"`
	ProxyType                 *ProxyType                  `json:"proxyType,omitempty"`
	ProxyUsername             *string                     `json:"proxyUsername"`
	SslCertPassword           *string                     `json:"sslCertPassword"`
	SslCertPath               *string                     `json:"sslCertPath"`
	SslPort                   *int32                      `json:"sslPort,omitempty"`
	TrustCgnatIpAddresses     *bool                       `json:"trustCgnatIpAddresses,omitempty"`
	UpdateAutomatically       *bool                       `json:"updateAutomatically,omitempty"`
	UpdateMechanism           *UpdateMechanism            `json:"updateMechanism,omitempty"`
	UpdateScriptPath          *string                     `json:"updateScriptPath"`
	UrlBase                   *string                     `json:"urlBase"`
	Username                  *string                     `json:"username"`
}

// IndexerCapabilityResource defines model for IndexerCapabilityResource.
type IndexerCapabilityResource struct {
	BookSearchParams  *[]BookSearchParam  `json:"bookSearchParams"`
	Categories        *[]IndexerCategory  `json:"categories"`
	Id                *int32              `json:"id,omitempty"`
	LimitsDefault     *int32              `json:"limitsDefault"`
	LimitsMax         *int32              `json:"limitsMax"`
	MovieSearchParams *[]MovieSearchParam `json:"movieSearchParams"`
	MusicSearchParams *[]MusicSearchParam `json:"musicSearchParams"`
	SearchParams      *[]SearchParam      `json:"searchParams"`
	SupportsRawSearch *bool               `json:"supportsRawSearch,omitempty"`
	TvSearchParams    *[]TvSearchParam    `json:"tvSearchParams"`
}

// IndexerCategory defines model for IndexerCategory.
type IndexerCategory struct {
	Description   *string            `json:"description"`
	Id            *int32             `json:"id,omitempty"`
	Name          *string            `json:"name"`
	SubCategories *[]IndexerCategory `json:"subCategories"`
}

// IndexerPrivacy defines model for IndexerPrivacy.
type IndexerPrivacy string

// IndexerProxyResource defines model for IndexerProxyResource.
type IndexerProxyResource struct {
	ConfigContract        *string                 `json:"configContract"`
	Fields                *[]Field                `json:"fields"`
	Id                    *int32                  `json:"id,omitempty"`
	Implementation        *string                 `json:"implementation"`
	ImplementationName    *string                 `json:"implementationName"`
	IncludeHealthWarnings *bool                   `json:"includeHealthWarnings,omitempty"`
	InfoLink              *string                 `json:"infoLink"`
	Link                  *string                 `json:"link"`
	Message               *ProviderMessage        `json:"message,omitempty"`
	Name                  *string                 `json:"name"`
	OnHealthIssue         *bool                   `json:"onHealthIssue,omitempty"`
	Presets               *[]IndexerProxyResource `json:"presets"`
	SupportsOnHealthIssue *bool                   `json:"supportsOnHealthIssue,omitempty"`
	Tags                  *[]int32                `json:"tags"`
	TestCommand           *string                 `json:"testCommand"`
}

// IndexerResource defines model for IndexerResource.
type IndexerResource struct {
	Added              *time.Time                 `json:"added,omitempty"`
	AppProfileId       *int32                     `json:"appProfileId,omitempty"`
	Capabilities       *IndexerCapabilityResource `json:"capabilities,omitempty"`
	ConfigContract     *string                    `json:"configContract"`
	DefinitionName     *string                    `json:"definitionName"`
	Description        *string                    `json:"description"`
	DownloadClientId   *int32                     `json:"downloadClientId,omitempty"`
	Enable             *bool                      `json:"enable,omitempty"`
	Encoding           *string                    `json:"encoding"`
	Fields             *[]Field                   `json:"fields"`
	Id                 *int32                     `json:"id,omitempty"`
	Implementation     *string                    `json:"implementation"`
	ImplementationName *string                    `json:"implementationName"`
	IndexerUrls        *[]string                  `json:"indexerUrls"`
	InfoLink           *string                    `json:"infoLink"`
	Language           *string                    `json:"language"`
	LegacyUrls         *[]string                  `json:"legacyUrls"`
	Message            *ProviderMessage           `json:"message,omitempty"`
	Name               *string                    `json:"name"`
	Presets            *[]IndexerResource         `json:"presets"`
	Priority           *int32                     `json:"priority,omitempty"`
	Privacy            *IndexerPrivacy            `json:"privacy,omitempty"`
	Protocol           *DownloadProtocol          `json:"protocol,omitempty"`
	Redirect           *bool                      `json:"redirect,omitempty"`
	SortName           *string                    `json:"sortName"`
	Status             *IndexerStatusResource     `json:"status,omitempty"`
	SupportsPagination *bool                      `json:"supportsPagination,omitempty"`
	SupportsRedirect   *bool                      `json:"supportsRedirect,omitempty"`
	SupportsRss        *bool                      `json:"supportsRss,omitempty"`
	SupportsSearch     *bool                      `json:"supportsSearch,omitempty"`
	Tags               *[]int32                   `json:"tags"`
}

// IndexerStatusResource defines model for IndexerStatusResource.
type IndexerStatusResource struct {
	DisabledTill      *time.Time `json:"disabledTill"`
	Id                *int32     `json:"id,omitempty"`
	IndexerId         *int32     `json:"indexerId,omitempty"`
	InitialFailure    *time.Time `json:"initialFailure"`
	MostRecentFailure *time.Time `json:"mostRecentFailure"`
}

// MovieSearchParam defines model for MovieSearchParam.
type MovieSearchParam string

// MusicSearchParam defines model for MusicSearchParam.
type MusicSearchParam string

// NotificationResource defines model for NotificationResource.
type NotificationResource struct {
	ConfigContract              *string                 `json:"configContract"`
	Fields                      *[]Field                `json:"fields"`
	Id                          *int32                  `json:"id,omitempty"`
	Implementation              *string                 `json:"implementation"`
	ImplementationName          *string                 `json:"implementationName"`
	IncludeHealthWarnings       *bool                   `json:"includeHealthWarnings,omitempty"`
	IncludeManualGrabs          *bool                   `json:"includeManualGrabs,omitempty"`
	InfoLink                    *string                 `json:"infoLink"`
	Link                        *string                 `json:"link"`
	Message                     *ProviderMessage        `json:"message,omitempty"`
	Name                        *string                 `json:"name"`
	OnApplicationUpdate         *bool                   `json:"onApplicationUpdate,omitempty"`
	OnGrab                      *bool                   `json:"onGrab,omitempty"`
	OnHealthIssue               *bool                   `json:"onHealthIssue,omitempty"`
	OnHealthRestored            *bool                   `json:"onHealthRestored,omitempty"`
	Presets                     *[]NotificationResource `json:"presets"`
	SupportsOnApplicationUpdate *bool                   `json:"supportsOnApplicationUpdate,omitempty"`
	SupportsOnGrab              *bool                   `json:"supportsOnGrab,omitempty"`
	SupportsOnHealthIssue       *bool                   `json:"supportsOnHealthIssue,omitempty"`
	SupportsOnHealthRestored    *bool                   `json:"supportsOnHealthRestored,omitempty"`
	Tags                        *[]int32                `json:"tags"`
	TestCommand                 *string                 `json:"testCommand"`
}

// PrivacyLevel defines model for PrivacyLevel.
type PrivacyLevel string

// ProviderMessage defines model for ProviderMessage.
type ProviderMessage struct {
	Message *string              `json:"message"`
	Type    *ProviderMessageType `json:"type,omitempty"`
}

// ProviderMessageType defines model for ProviderMessageType.
type ProviderMessageType string

// ProxyType defines model for ProxyType.
type ProxyType string

// SearchParam defines model for SearchParam.
type SearchParam string

// SelectOption defines model for SelectOption.
type SelectOption struct {
	Hint        *string `json:"hint"`
	Name        *string `json:"name"`
	Order       *int32  `json:"order,omitempty"`
	ParentValue *int32  `json:"parentValue"`
	Value       *int32  `json:"value,omitempty"`
}

// TagResource defines model for TagResource.
type TagResource struct {
	Id    *int32  `json:"id,omitempty"`
	Label *string `json:"label"`
}

// TvSearchParam defines model for TvSearchParam.
type TvSearchParam string

// UpdateMechanism defines model for UpdateMechanism.
type UpdateMechanism string

// PostApiV1CommandJSONRequestBody defines body for PostApiV1Command for application/json ContentType.
type PostApiV1CommandJSONRequestBody = CommandResource

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// PostApiV1CommandWithBody request with any body
	PostApiV1CommandWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostApiV1Command(ctx context.Context, body PostApiV1CommandJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiV1CommandId request
	GetApiV1CommandId(ctx context.Context, id int32, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiV1ConfigHost request
	GetApiV1ConfigHost(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiV1SystemBackup request
	GetApiV1SystemBackup(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostApiV1SystemRestart request
	PostApiV1SystemRestart(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiV1Tag request
	GetApiV1Tag(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) PostApiV1CommandWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiV1CommandRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiV1Command(ctx context.Context, body PostApiV1CommandJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiV1CommandRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiV1CommandId(ctx context.Context, id int32, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiV1CommandIdRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiV1ConfigHost(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiV1ConfigHostRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiV1SystemBackup(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiV1SystemBackupRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiV1SystemRestart(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiV1SystemRestartRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiV1Tag(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiV1TagRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewPostApiV1CommandRequest calls the generic PostApiV1Command builder with application/json body
func NewPostApiV1CommandRequest(server string, body PostApiV1CommandJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostApiV1CommandRequestWithBody(server, "application/json", bodyReader)
}

// NewPostApiV1CommandRequestWithBody generates requests for PostApiV1Command with any type of body
func NewPostApiV1CommandRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/command")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetApiV1CommandIdRequest generates requests for GetApiV1CommandId
func NewGetApiV1CommandIdRequest(server string, id int32) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/command/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetApiV1ConfigHostRequest generates requests for GetApiV1ConfigHost
func NewGetApiV1ConfigHostRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/config/host")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetApiV1SystemBackupRequest generates requests for GetApiV1SystemBackup
func NewGetApiV1SystemBackupRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/system/backup")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostApiV1SystemRestartRequest generates requests for PostApiV1SystemRestart
func NewPostApiV1SystemRestartRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/system/restart")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetApiV1TagRequest generates requests for GetApiV1Tag
func NewGetApiV1TagRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/tag")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// PostApiV1CommandWithBodyWithResponse request with any body
	PostApiV1CommandWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiV1CommandResponse, error)

	PostApiV1CommandWithResponse(ctx context.Context, body PostApiV1CommandJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiV1CommandResponse, error)

	// GetApiV1CommandIdWithResponse request
	GetApiV1CommandIdWithResponse(ctx context.Context, id int32, reqEditors ...RequestEditorFn) (*GetApiV1CommandIdResponse, error)

	// GetApiV1ConfigHostWithResponse request
	GetApiV1ConfigHostWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiV1ConfigHostResponse, error)

	// GetApiV1SystemBackupWithResponse request
	GetApiV1SystemBackupWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiV1SystemBackupResponse, error)

	// PostApiV1SystemRestartWithResponse request
	PostApiV1SystemRestartWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*PostApiV1SystemRestartResponse, error)

	// GetApiV1TagWithResponse request
	GetApiV1TagWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiV1TagResponse, error)
}

type PostApiV1CommandResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *CommandResource
}

// Status returns HTTPResponse.Status
func (r PostApiV1CommandResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostApiV1CommandResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetApiV1CommandIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *CommandResource
}

// Status returns HTTPResponse.Status
func (r GetApiV1CommandIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiV1CommandIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetApiV1ConfigHostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *HostConfigResource
}

// Status returns HTTPResponse.Status
func (r GetApiV1ConfigHostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiV1ConfigHostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetApiV1SystemBackupResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]BackupResource
}

// Status returns HTTPResponse.Status
func (r GetApiV1SystemBackupResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiV1SystemBackupResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostApiV1SystemRestartResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r PostApiV1SystemRestartResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostApiV1SystemRestartResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetApiV1TagResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]TagResource
}

// Status returns HTTPResponse.Status
func (r GetApiV1TagResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiV1TagResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// PostApiV1CommandWithBodyWithResponse request with arbitrary body returning *PostApiV1CommandResponse
func (c *ClientWithResponses) PostApiV1CommandWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiV1CommandResponse, error) {
	rsp, err := c.PostApiV1CommandWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiV1CommandResponse(rsp)
}

func (c *ClientWithResponses) PostApiV1CommandWithResponse(ctx context.Context, body PostApiV1CommandJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiV1CommandResponse, error) {
	rsp, err := c.PostApiV1Command(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiV1CommandResponse(rsp)
}

// GetApiV1CommandIdWithResponse request returning *GetApiV1CommandIdResponse
func (c *ClientWithResponses) GetApiV1CommandIdWithResponse(ctx context.Context, id int32, reqEditors ...RequestEditorFn) (*GetApiV1CommandIdResponse, error) {
	rsp, err := c.GetApiV1CommandId(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiV1CommandIdResponse(rsp)
}

// GetApiV1ConfigHostWithResponse request returning *GetApiV1ConfigHostResponse
func (c *ClientWithResponses) GetApiV1ConfigHostWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiV1ConfigHostResponse, error) {
	rsp, err := c.GetApiV1ConfigHost(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiV1ConfigHostResponse(rsp)
}

// GetApiV1SystemBackupWithResponse request returning *GetApiV1SystemBackupResponse
func (c *ClientWithResponses) GetApiV1SystemBackupWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiV1SystemBackupResponse, error) {
	rsp, err := c.GetApiV1SystemBackup(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiV1SystemBackupResponse(rsp)
}

// PostApiV1SystemRestartWithResponse request returning *PostApiV1SystemRestartResponse
func (c *ClientWithResponses) PostApiV1SystemRestartWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*PostApiV1SystemRestartResponse, error) {
	rsp, err := c.PostApiV1SystemRestart(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiV1SystemRestartResponse(rsp)
}

// GetApiV1TagWithResponse request returning *GetApiV1TagResponse
func (c *ClientWithResponses) GetApiV1TagWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiV1TagResponse, error) {
	rsp, err := c.GetApiV1Tag(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiV1TagResponse(rsp)
}

// ParsePostApiV1CommandResponse parses an HTTP response from a PostApiV1CommandWithResponse call
func ParsePostApiV1CommandResponse(rsp *http.Response) (*PostApiV1CommandResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostApiV1CommandResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CommandResource
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetApiV1CommandIdResponse parses an HTTP response from a GetApiV1CommandIdWithResponse call
func ParseGetApiV1CommandIdResponse(rsp *http.Response) (*GetApiV1CommandIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiV1CommandIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CommandResource
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetApiV1ConfigHostResponse parses an HTTP response from a GetApiV1ConfigHostWithResponse call
func ParseGetApiV1ConfigHostResponse(rsp *http.Response) (*GetApiV1ConfigHostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiV1ConfigHostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest HostConfigResource
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetApiV1SystemBackupResponse parses an HTTP response from a GetApiV1SystemBackupWithResponse call
func ParseGetApiV1SystemBackupResponse(rsp *http.Response) (*GetApiV1SystemBackupResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiV1SystemBackupResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []BackupResource
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostApiV1SystemRestartResponse parses an HTTP response from a PostApiV1SystemRestartWithResponse call
func ParsePostApiV1SystemRestartResponse(rsp *http.Response) (*PostApiV1SystemRestartResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostApiV1SystemRestartResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetApiV1TagResponse parses an HTTP response from a GetApiV1TagWithResponse call
func ParseGetApiV1TagResponse(rsp *http.Response) (*GetApiV1TagResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiV1TagResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []TagResource
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
