// Package sonarr provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package sonarr

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

const (
	X_Api_KeyScopes = "X_Api_Key.Scopes"
	ApikeyScopes    = "apikey.Scopes"
)

// Defines values for AuthenticationRequiredType.
const (
	AuthenticationRequiredTypeDisabledForLocalAddresses AuthenticationRequiredType = "disabledForLocalAddresses"
	AuthenticationRequiredTypeEnabled                   AuthenticationRequiredType = "enabled"
)

// Defines values for AuthenticationType.
const (
	AuthenticationTypeBasic    AuthenticationType = "basic"
	AuthenticationTypeExternal AuthenticationType = "external"
	AuthenticationTypeForms    AuthenticationType = "forms"
	AuthenticationTypeNone     AuthenticationType = "none"
)

// Defines values for BackupType.
const (
	BackupTypeManual    BackupType = "manual"
	BackupTypeScheduled BackupType = "scheduled"
	BackupTypeUpdate    BackupType = "update"
)

// Defines values for CertificateValidationType.
const (
	CertificateValidationTypeDisabled                  CertificateValidationType = "disabled"
	CertificateValidationTypeDisabledForLocalAddresses CertificateValidationType = "disabledForLocalAddresses"
	CertificateValidationTypeEnabled                   CertificateValidationType = "enabled"
)

// Defines values for CommandPriority.
const (
	CommandPriorityHigh   CommandPriority = "high"
	CommandPriorityLow    CommandPriority = "low"
	CommandPriorityNormal CommandPriority = "normal"
)

// Defines values for CommandResult.
const (
	CommandResultSuccessful   CommandResult = "successful"
	CommandResultUnknown      CommandResult = "unknown"
	CommandResultUnsuccessful CommandResult = "unsuccessful"
)

// Defines values for CommandStatus.
const (
	CommandStatusAborted   CommandStatus = "aborted"
	CommandStatusCancelled CommandStatus = "cancelled"
	CommandStatusCompleted CommandStatus = "completed"
	CommandStatusFailed    CommandStatus = "failed"
	CommandStatusOrphaned  CommandStatus = "orphaned"
	CommandStatusQueued    CommandStatus = "queued"
	CommandStatusStarted   CommandStatus = "started"
)

// Defines values for CommandTrigger.
const (
	CommandTriggerManual      CommandTrigger = "manual"
	CommandTriggerScheduled   CommandTrigger = "scheduled"
	CommandTriggerUnspecified CommandTrigger = "unspecified"
)

// Defines values for DatabaseType.
const (
	PostgreSQL DatabaseType = "postgreSQL"
	SqLite     DatabaseType = "sqLite"
)

// Defines values for DownloadProtocol.
const (
	DownloadProtocolTorrent DownloadProtocol = "torrent"
	DownloadProtocolUnknown DownloadProtocol = "unknown"
	DownloadProtocolUsenet  DownloadProtocol = "usenet"
)

// Defines values for ImportListType.
const (
	Advanced ImportListType = "advanced"
	Other    ImportListType = "other"
	Plex     ImportListType = "plex"
	Program  ImportListType = "program"
	Simkl    ImportListType = "simkl"
	Trakt    ImportListType = "trakt"
)

// Defines values for MediaCoverTypes.
const (
	MediaCoverTypesBanner     MediaCoverTypes = "banner"
	MediaCoverTypesClearlogo  MediaCoverTypes = "clearlogo"
	MediaCoverTypesFanart     MediaCoverTypes = "fanart"
	MediaCoverTypesHeadshot   MediaCoverTypes = "headshot"
	MediaCoverTypesPoster     MediaCoverTypes = "poster"
	MediaCoverTypesScreenshot MediaCoverTypes = "screenshot"
	MediaCoverTypesUnknown    MediaCoverTypes = "unknown"
)

// Defines values for MonitorTypes.
const (
	MonitorTypesAll               MonitorTypes = "all"
	MonitorTypesExisting          MonitorTypes = "existing"
	MonitorTypesFirstSeason       MonitorTypes = "firstSeason"
	MonitorTypesFuture            MonitorTypes = "future"
	MonitorTypesLastSeason        MonitorTypes = "lastSeason"
	MonitorTypesLatestSeason      MonitorTypes = "latestSeason"
	MonitorTypesMissing           MonitorTypes = "missing"
	MonitorTypesMonitorSpecials   MonitorTypes = "monitorSpecials"
	MonitorTypesNone              MonitorTypes = "none"
	MonitorTypesPilot             MonitorTypes = "pilot"
	MonitorTypesRecent            MonitorTypes = "recent"
	MonitorTypesSkip              MonitorTypes = "skip"
	MonitorTypesUnknown           MonitorTypes = "unknown"
	MonitorTypesUnmonitorSpecials MonitorTypes = "unmonitorSpecials"
)

// Defines values for NewItemMonitorTypes.
const (
	All  NewItemMonitorTypes = "all"
	None NewItemMonitorTypes = "none"
)

// Defines values for PrivacyLevel.
const (
	PrivacyLevelApiKey   PrivacyLevel = "apiKey"
	PrivacyLevelNormal   PrivacyLevel = "normal"
	PrivacyLevelPassword PrivacyLevel = "password"
	PrivacyLevelUserName PrivacyLevel = "userName"
)

// Defines values for ProviderMessageType.
const (
	Error   ProviderMessageType = "error"
	Info    ProviderMessageType = "info"
	Warning ProviderMessageType = "warning"
)

// Defines values for ProxyType.
const (
	Http   ProxyType = "http"
	Socks4 ProxyType = "socks4"
	Socks5 ProxyType = "socks5"
)

// Defines values for QualitySource.
const (
	QualitySourceBluray        QualitySource = "bluray"
	QualitySourceBlurayRaw     QualitySource = "blurayRaw"
	QualitySourceDvd           QualitySource = "dvd"
	QualitySourceTelevision    QualitySource = "television"
	QualitySourceTelevisionRaw QualitySource = "televisionRaw"
	QualitySourceUnknown       QualitySource = "unknown"
	QualitySourceWeb           QualitySource = "web"
	QualitySourceWebRip        QualitySource = "webRip"
)

// Defines values for RuntimeMode.
const (
	Console RuntimeMode = "console"
	Service RuntimeMode = "service"
	Tray    RuntimeMode = "tray"
)

// Defines values for SeriesStatusType.
const (
	Continuing SeriesStatusType = "continuing"
	Deleted    SeriesStatusType = "deleted"
	Ended      SeriesStatusType = "ended"
	Upcoming   SeriesStatusType = "upcoming"
)

// Defines values for SeriesTypes.
const (
	Anime    SeriesTypes = "anime"
	Daily    SeriesTypes = "daily"
	Standard SeriesTypes = "standard"
)

// Defines values for UpdateMechanism.
const (
	Apt      UpdateMechanism = "apt"
	BuiltIn  UpdateMechanism = "builtIn"
	Docker   UpdateMechanism = "docker"
	External UpdateMechanism = "external"
	Script   UpdateMechanism = "script"
)

// AddSeriesOptions defines model for AddSeriesOptions.
type AddSeriesOptions struct {
	IgnoreEpisodesWithFiles      *bool         `json:"ignoreEpisodesWithFiles,omitempty"`
	IgnoreEpisodesWithoutFiles   *bool         `json:"ignoreEpisodesWithoutFiles,omitempty"`
	Monitor                      *MonitorTypes `json:"monitor,omitempty"`
	SearchForCutoffUnmetEpisodes *bool         `json:"searchForCutoffUnmetEpisodes,omitempty"`
	SearchForMissingEpisodes     *bool         `json:"searchForMissingEpisodes,omitempty"`
}

// AlternateTitleResource defines model for AlternateTitleResource.
type AlternateTitleResource struct {
	Comment           *string `json:"comment"`
	SceneOrigin       *string `json:"sceneOrigin"`
	SceneSeasonNumber *int32  `json:"sceneSeasonNumber"`
	SeasonNumber      *int32  `json:"seasonNumber"`
	Title             *string `json:"title"`
}

// AuthenticationRequiredType defines model for AuthenticationRequiredType.
type AuthenticationRequiredType string

// AuthenticationType defines model for AuthenticationType.
type AuthenticationType string

// BackupResource defines model for BackupResource.
type BackupResource struct {
	Id   *int32      `json:"id,omitempty"`
	Name *string     `json:"name"`
	Path *string     `json:"path"`
	Size *int64      `json:"size,omitempty"`
	Time *time.Time  `json:"time,omitempty"`
	Type *BackupType `json:"type,omitempty"`
}

// BackupType defines model for BackupType.
type BackupType string

// CertificateValidationType defines model for CertificateValidationType.
type CertificateValidationType string

// Command defines model for Command.
type Command struct {
	ClientUserAgent     *string         `json:"clientUserAgent"`
	CompletionMessage   *string         `json:"completionMessage"`
	IsExclusive         *bool           `json:"isExclusive,omitempty"`
	IsLongRunning       *bool           `json:"isLongRunning,omitempty"`
	LastExecutionTime   *time.Time      `json:"lastExecutionTime"`
	LastStartTime       *time.Time      `json:"lastStartTime"`
	Name                *string         `json:"name"`
	RequiresDiskAccess  *bool           `json:"requiresDiskAccess,omitempty"`
	SendUpdatesToClient *bool           `json:"sendUpdatesToClient,omitempty"`
	SuppressMessages    *bool           `json:"suppressMessages,omitempty"`
	Trigger             *CommandTrigger `json:"trigger,omitempty"`
	UpdateScheduledTask *bool           `json:"updateScheduledTask,omitempty"`
}

// CommandPriority defines model for CommandPriority.
type CommandPriority string

// CommandResource defines model for CommandResource.
type CommandResource struct {
	Body                *Command         `json:"body,omitempty"`
	ClientUserAgent     *string          `json:"clientUserAgent"`
	CommandName         *string          `json:"commandName"`
	Duration            *string          `json:"duration"`
	Ended               *time.Time       `json:"ended"`
	Exception           *string          `json:"exception"`
	Id                  *int32           `json:"id,omitempty"`
	LastExecutionTime   *time.Time       `json:"lastExecutionTime"`
	Message             *string          `json:"message"`
	Name                *string          `json:"name"`
	Priority            *CommandPriority `json:"priority,omitempty"`
	Queued              *time.Time       `json:"queued,omitempty"`
	Result              *CommandResult   `json:"result,omitempty"`
	SendUpdatesToClient *bool            `json:"sendUpdatesToClient,omitempty"`
	Started             *time.Time       `json:"started"`
	StateChangeTime     *time.Time       `json:"stateChangeTime"`
	Status              *CommandStatus   `json:"status,omitempty"`
	Trigger             *CommandTrigger  `json:"trigger,omitempty"`
	UpdateScheduledTask *bool            `json:"updateScheduledTask,omitempty"`
}

// CommandResult defines model for CommandResult.
type CommandResult string

// CommandStatus defines model for CommandStatus.
type CommandStatus string

// CommandTrigger defines model for CommandTrigger.
type CommandTrigger string

// CustomFormatSpecificationSchema defines model for CustomFormatSpecificationSchema.
type CustomFormatSpecificationSchema struct {
	Fields             *[]Field                           `json:"fields"`
	Id                 *int32                             `json:"id,omitempty"`
	Implementation     *string                            `json:"implementation"`
	ImplementationName *string                            `json:"implementationName"`
	InfoLink           *string                            `json:"infoLink"`
	Name               *string                            `json:"name"`
	Negate             *bool                              `json:"negate,omitempty"`
	Presets            *[]CustomFormatSpecificationSchema `json:"presets"`
	Required           *bool                              `json:"required,omitempty"`
}

// DatabaseType defines model for DatabaseType.
type DatabaseType string

// DownloadClientResource defines model for DownloadClientResource.
type DownloadClientResource struct {
	ConfigContract           *string                   `json:"configContract"`
	Enable                   *bool                     `json:"enable,omitempty"`
	Fields                   *[]Field                  `json:"fields"`
	Id                       *int32                    `json:"id,omitempty"`
	Implementation           *string                   `json:"implementation"`
	ImplementationName       *string                   `json:"implementationName"`
	InfoLink                 *string                   `json:"infoLink"`
	Message                  *ProviderMessage          `json:"message,omitempty"`
	Name                     *string                   `json:"name"`
	Presets                  *[]DownloadClientResource `json:"presets"`
	Priority                 *int32                    `json:"priority,omitempty"`
	Protocol                 *DownloadProtocol         `json:"protocol,omitempty"`
	RemoveCompletedDownloads *bool                     `json:"removeCompletedDownloads,omitempty"`
	RemoveFailedDownloads    *bool                     `json:"removeFailedDownloads,omitempty"`
	Tags                     *[]int32                  `json:"tags"`
}

// DownloadProtocol defines model for DownloadProtocol.
type DownloadProtocol string

// Field defines model for Field.
type Field struct {
	Advanced                    *bool           `json:"advanced,omitempty"`
	HelpLink                    *string         `json:"helpLink"`
	HelpText                    *string         `json:"helpText"`
	HelpTextWarning             *string         `json:"helpTextWarning"`
	Hidden                      *string         `json:"hidden"`
	IsFloat                     *bool           `json:"isFloat,omitempty"`
	Label                       *string         `json:"label"`
	Name                        *string         `json:"name"`
	Order                       *int32          `json:"order,omitempty"`
	Placeholder                 *string         `json:"placeholder"`
	Privacy                     *PrivacyLevel   `json:"privacy,omitempty"`
	Section                     *string         `json:"section"`
	SelectOptions               *[]SelectOption `json:"selectOptions"`
	SelectOptionsProviderAction *string         `json:"selectOptionsProviderAction"`
	Type                        *string         `json:"type"`
	Unit                        *string         `json:"unit"`
	Value                       interface{}     `json:"value"`
}

// HostConfigResource defines model for HostConfigResource.
type HostConfigResource struct {
	AllowedHosts              *string                     `json:"allowedHosts"`
	AnalyticsEnabled          *bool                       `json:"analyticsEnabled,omitempty"`
	ApiKey                    *string                     `json:"apiKey"`
	ApplicationUrl            *string                     `json:"applicationUrl"`
	AuthenticationMethod      *AuthenticationType         `json:"authenticationMethod,omitempty"`
	AuthenticationRequired    *AuthenticationRequiredType `json:"authenticationRequired,omitempty"`
	BackupFolder              *string                     `json:"backupFolder"`
	BackupInterval            *int32                      `json:"backupInterval,omitempty"`
	BackupRetention           *int32                      `json:"backupRetention,omitempty"`
	BindAddress               *string                     `json:"bindAddress"`
	Branch                    *string                     `json:"branch"`
	CertificateValidation     *CertificateValidationType  `json:"certificateValidation,omitempty"`
	ConsoleLogLevel           *string                     `json:"consoleLogLevel"`
	EnableSsl                 *bool                       `json:"enableSsl,omitempty"`
	Id                        *int32                      `json:"id,omitempty"`
	InstanceName              *string                     `json:"instanceName"`
	LaunchBrowser             *bool                       `json:"launchBrowser,omitempty"`
	LogLevel                  *string                     `json:"logLevel"`
	LogSizeLimit              *int32                      `json:"logSizeLimit,omitempty"`
	Password                  *string                     `json:"password"`
	PasswordConfirmation      *string                     `json:"passwordConfirmation"`
	Port                      *int32                      `json:"port,omitempty"`
	ProxyBypassFilter         *string                     `json:"proxyBypassFilter"`
	ProxyBypassLocalAddresses *bool                       `json:"proxyBypassLocalAddresses,omitempty"`
	ProxyEnabled              *bool                       `json:"proxyEnabled,omitempty"`
	ProxyHostname             *string                     `json:"proxyHostname"`
	ProxyPassword             *string                     `json:"proxyPassword"`
	ProxyPort                 *int32                      `json:"proxyPort,omitempty"`
	ProxyType                 *ProxyType                  `json:"proxyType,omitempty"`
	ProxyUsername             *string                     `json:"proxyUsername"`
	SslCertPassword           *string                     `json:"sslCertPassword"`
	SslCertPath               *string                     `json:"sslCertPath"`
	SslPort                   *int32                      `json:"sslPort,omitempty"`
	TrustCgnatIpAddresses     *bool                       `json:"trustCgnatIpAddresses,omitempty"`
	TrustedNetworks           *string                     `json:"trustedNetworks"`
	UpdateAutomatically       *bool                       `json:"updateAutomatically,omitempty"`
	UpdateMechanism           *UpdateMechanism            `json:"updateMechanism,omitempty"`
	UpdateScriptPath          *string                     `json:"updateScriptPath"`
	UrlBase                   *string                     `json:"urlBase"`
	Username                  *string                     `json:"username"`
}

// ImportListResource defines model for ImportListResource.
type ImportListResource struct {
	ConfigContract           *string               `json:"configContract"`
	EnableAutomaticAdd       *bool                 `json:"enableAutomaticAdd,omitempty"`
	Fields                   *[]Field              `json:"fields"`
	Id                       *int32                `json:"id,omitempty"`
	Implementation           *string               `json:"implementation"`
	ImplementationName       *string               `json:"implementationName"`
	InfoLink                 *string               `json:"infoLink"`
	ListOrder                *int32                `json:"listOrder,omitempty"`
	ListType                 *ImportListType       `json:"listType,omitempty"`
	Message                  *ProviderMessage      `json:"message,omitempty"`
	MinRefreshInterval       *string               `json:"minRefreshInterval,omitempty"`
	MonitorNewItems          *NewItemMonitorTypes  `json:"monitorNewItems,omitempty"`
	Name                     *string               `json:"name"`
	Presets                  *[]ImportListResource `json:"presets"`
	QualityProfileId         *int32                `json:"qualityProfileId,omitempty"`
	RootFolderPath           *string               `json:"rootFolderPath"`
	SearchForMissingEpisodes *bool                 `json:"searchForMissingEpisodes,omitempty"`
	SeasonFolder             *bool                 `json:"seasonFolder,omitempty"`
	SeriesType               *SeriesTypes          `json:"seriesType,omitempty"`
	ShouldMonitor            *MonitorTypes         `json:"shouldMonitor,omitempty"`
	Tags                     *[]int32              `json:"tags"`
}

// ImportListType defines model for ImportListType.
type ImportListType string

// IndexerResource defines model for IndexerResource.
type IndexerResource struct {
	ConfigContract                      *string            `json:"configContract"`
	DownloadClientId                    *int32             `json:"downloadClientId,omitempty"`
	EnableAutomaticSearch               *bool              `json:"enableAutomaticSearch,omitempty"`
	EnableInteractiveSearch             *bool              `json:"enableInteractiveSearch,omitempty"`
	EnableRss                           *bool              `json:"enableRss,omitempty"`
	Fields                              *[]Field           `json:"fields"`
	Id                                  *int32             `json:"id,omitempty"`
	Implementation                      *string            `json:"implementation"`
	ImplementationName                  *string            `json:"implementationName"`
	InfoLink                            *string            `json:"infoLink"`
	Message                             *ProviderMessage   `json:"message,omitempty"`
	Name                                *string            `json:"name"`
	Presets                             *[]IndexerResource `json:"presets"`
	Priority                            *int32             `json:"priority,omitempty"`
	Protocol                            *DownloadProtocol  `json:"protocol,omitempty"`
	SeasonSearchMaximumSingleEpisodeAge *int32             `json:"seasonSearchMaximumSingleEpisodeAge,omitempty"`
	SupportsRss                         *bool              `json:"supportsRss,omitempty"`
	SupportsSearch                      *bool              `json:"supportsSearch,omitempty"`
	Tags                                *[]int32           `json:"tags"`
}

// Language defines model for Language.
type Language struct {
	Id   *int32  `json:"id,omitempty"`
	Name *string `json:"name"`
}

// MediaCover defines model for MediaCover.
type MediaCover struct {
	CoverType *MediaCoverTypes `json:"coverType,omitempty"`
	RemoteUrl *string          `json:"remoteUrl"`
	Url       *string          `json:"url"`
}

// MediaCoverTypes defines model for MediaCoverTypes.
type MediaCoverTypes string

// MetadataResource defines model for MetadataResource.
type MetadataResource struct {
	ConfigContract     *string             `json:"configContract"`
	Enable             *bool               `json:"enable,omitempty"`
	Fields             *[]Field            `json:"fields"`
	Id                 *int32              `json:"id,omitempty"`
	Implementation     *string             `json:"implementation"`
	ImplementationName *string             `json:"implementationName"`
	InfoLink           *string             `json:"infoLink"`
	Message            *ProviderMessage    `json:"message,omitempty"`
	Name               *string             `json:"name"`
	Presets            *[]MetadataResource `json:"presets"`
	Tags               *[]int32            `json:"tags"`
}

// MonitorTypes defines model for MonitorTypes.
type MonitorTypes string

// NewItemMonitorTypes defines model for NewItemMonitorTypes.
type NewItemMonitorTypes string

// NotificationResource defines model for NotificationResource.
type NotificationResource struct {
	ConfigContract                        *string                 `json:"configContract"`
	Fields                                *[]Field                `json:"fields"`
	Id                                    *int32                  `json:"id,omitempty"`
	Implementation                        *string                 `json:"implementation"`
	ImplementationName                    *string                 `json:"implementationName"`
	IncludeHealthWarnings                 *bool                   `json:"includeHealthWarnings,omitempty"`
	InfoLink                              *string                 `json:"infoLink"`
	Link                                  *string                 `json:"link"`
	Message                               *ProviderMessage        `json:"message,omitempty"`
	Name                                  *string                 `json:"name"`
	OnApplicationUpdate                   *bool                   `json:"onApplicationUpdate,omitempty"`
	OnDownload                            *bool                   `json:"onDownload,omitempty"`
	OnEpisodeFileDelete                   *bool                   `json:"onEpisodeFileDelete,omitempty"`
	OnEpisodeFileDeleteForUpgrade         *bool                   `json:"onEpisodeFileDeleteForUpgrade,omitempty"`
	OnGrab                                *bool                   `json:"onGrab,omitempty"`
	OnHealthIssue                         *bool                   `json:"onHealthIssue,omitempty"`
	OnHealthRestored                      *bool                   `json:"onHealthRestored,omitempty"`
	OnImportComplete                      *bool                   `json:"onImportComplete,omitempty"`
	OnManualInteractionRequired           *bool                   `json:"onManualInteractionRequired,omitempty"`
	OnRename                              *bool                   `json:"onRename,omitempty"`
	OnSeriesAdd                           *bool                   `json:"onSeriesAdd,omitempty"`
	OnSeriesDelete                        *bool                   `json:"onSeriesDelete,omitempty"`
	OnUpgrade                             *bool                   `json:"onUpgrade,omitempty"`
	Presets                               *[]NotificationResource `json:"presets"`
	SupportsOnApplicationUpdate           *bool                   `json:"supportsOnApplicationUpdate,omitempty"`
	SupportsOnDownload                    *bool                   `json:"supportsOnDownload,omitempty"`
	SupportsOnEpisodeFileDelete           *bool                   `json:"supportsOnEpisodeFileDelete,omitempty"`
	SupportsOnEpisodeFileDeleteForUpgrade *bool                   `json:"supportsOnEpisodeFileDeleteForUpgrade,omitempty"`
	SupportsOnGrab                        *bool                   `json:"supportsOnGrab,omitempty"`
	SupportsOnHealthIssue                 *bool                   `json:"supportsOnHealthIssue,omitempty"`
	SupportsOnHealthRestored              *bool                   `json:"supportsOnHealthRestored,omitempty"`
	SupportsOnImportComplete              *bool                   `json:"supportsOnImportComplete,omitempty"`
	SupportsOnManualInteractionRequired   *bool                   `json:"supportsOnManualInteractionRequired,omitempty"`
	SupportsOnRename                      *bool                   `json:"supportsOnRename,omitempty"`
	SupportsOnSeriesAdd                   *bool                   `json:"supportsOnSeriesAdd,omitempty"`
	SupportsOnSeriesDelete                *bool                   `json:"supportsOnSeriesDelete,omitempty"`
	SupportsOnUpgrade                     *bool                   `json:"supportsOnUpgrade,omitempty"`
	Tags                                  *[]int32                `json:"tags"`
	TestCommand                           *string                 `json:"testCommand"`
}

// PrivacyLevel defines model for PrivacyLevel.
type PrivacyLevel string

// ProviderMessage defines model for ProviderMessage.
type ProviderMessage struct {
	Message *string              `json:"message"`
	Type    *ProviderMessageType `json:"type,omitempty"`
}

// ProviderMessageType defines model for ProviderMessageType.
type ProviderMessageType string

// ProxyType defines model for ProxyType.
type ProxyType string

// Quality defines model for Quality.
type Quality struct {
	Id         *int32         `json:"id,omitempty"`
	Name       *string        `json:"name"`
	Resolution *int32         `json:"resolution,omitempty"`
	Source     *QualitySource `json:"source,omitempty"`
}

// QualityProfileQualityItemResource defines model for QualityProfileQualityItemResource.
type QualityProfileQualityItemResource struct {
	Allowed *bool                                `json:"allowed,omitempty"`
	Id      *int32                               `json:"id,omitempty"`
	Items   *[]QualityProfileQualityItemResource `json:"items"`
	Name    *string                              `json:"name"`
	Quality *Quality                             `json:"quality,omitempty"`
}

// QualitySource defines model for QualitySource.
type QualitySource string

// Ratings defines model for Ratings.
type Ratings struct {
	Value *float64 `json:"value,omitempty"`
	Votes *int32   `json:"votes,omitempty"`
}

// RuntimeMode defines model for RuntimeMode.
type RuntimeMode string

// SeasonResource defines model for SeasonResource.
type SeasonResource struct {
	Images       *[]MediaCover             `json:"images"`
	Monitored    *bool                     `json:"monitored,omitempty"`
	SeasonNumber *int32                    `json:"seasonNumber,omitempty"`
	Statistics   *SeasonStatisticsResource `json:"statistics,omitempty"`
}

// SeasonStatisticsResource defines model for SeasonStatisticsResource.
type SeasonStatisticsResource struct {
	EpisodeCount      *int32     `json:"episodeCount,omitempty"`
	EpisodeFileCount  *int32     `json:"episodeFileCount,omitempty"`
	NextAiring        *time.Time `json:"nextAiring"`
	PercentOfEpisodes *float64   `json:"percentOfEpisodes,omitempty"`
	PreviousAiring    *time.Time `json:"previousAiring"`
	ReleaseGroups     *[]string  `json:"releaseGroups"`
	SizeOnDisk        *int64     `json:"sizeOnDisk,omitempty"`
	TotalEpisodeCount *int32     `json:"totalEpisodeCount,omitempty"`
}

// SelectOption defines model for SelectOption.
type SelectOption struct {
	Hint  *string `json:"hint"`
	Name  *string `json:"name"`
	Order *int32  `json:"order,omitempty"`
	Value *int32  `json:"value,omitempty"`
}

// SeriesResource defines model for SeriesResource.
type SeriesResource struct {
	AddOptions      *AddSeriesOptions         `json:"addOptions,omitempty"`
	Added           *time.Time                `json:"added,omitempty"`
	AirTime         *string                   `json:"airTime"`
	AlternateTitles *[]AlternateTitleResource `json:"alternateTitles"`
	Certification   *string                   `json:"certification"`
	CleanTitle      *string                   `json:"cleanTitle"`
	Ended           *bool                     `json:"ended,omitempty"`
	EpisodesChanged *bool                     `json:"episodesChanged"`
	FirstAired      *time.Time                `json:"firstAired"`
	Folder          *string                   `json:"folder"`
	Genres          *[]string                 `json:"genres"`
	Id              *int32                    `json:"id,omitempty"`
	Images          *[]MediaCover             `json:"images"`
	ImdbId          *string                   `json:"imdbId"`
	// Deprecated: this property has been marked as deprecated upstream, but no `x-deprecated-reason` was set
	LanguageProfileId *int32                    `json:"languageProfileId,omitempty"`
	LastAired         *time.Time                `json:"lastAired"`
	MonitorNewItems   *NewItemMonitorTypes      `json:"monitorNewItems,omitempty"`
	Monitored         *bool                     `json:"monitored,omitempty"`
	Network           *string                   `json:"network"`
	NextAiring        *time.Time                `json:"nextAiring"`
	OriginalLanguage  *Language                 `json:"originalLanguage,omitempty"`
	Overview          *string                   `json:"overview"`
	Path              *string                   `json:"path"`
	PreviousAiring    *time.Time                `json:"previousAiring"`
	ProfileName       *string                   `json:"profileName"`
	QualityProfileId  *int32                    `json:"qualityProfileId,omitempty"`
	Ratings           *Ratings                  `json:"ratings,omitempty"`
	RemotePoster      *string                   `json:"remotePoster"`
	RootFolderPath    *string                   `json:"rootFolderPath"`
	Runtime           *int32                    `json:"runtime,omitempty"`
	SeasonFolder      *bool                     `json:"seasonFolder,omitempty"`
	Seasons           *[]SeasonResource         `json:"seasons"`
	SeriesType        *SeriesTypes              `json:"seriesType,omitempty"`
	SortTitle         *string                   `json:"sortTitle"`
	Statistics        *SeriesStatisticsResource `json:"statistics,omitempty"`
	Status            *SeriesStatusType         `json:"status,omitempty"`
	Tags              *[]int32                  `json:"tags"`
	Title             *string                   `json:"title"`
	TitleSlug         *string                   `json:"titleSlug"`
	TmdbId            *int32                    `json:"tmdbId,omitempty"`
	TvMazeId          *int32                    `json:"tvMazeId,omitempty"`
	TvRageId          *int32                    `json:"tvRageId,omitempty"`
	TvdbId            *int32                    `json:"tvdbId,omitempty"`
	UseSceneNumbering *bool                     `json:"useSceneNumbering,omitempty"`
	Year              *int32                    `json:"year,omitempty"`
}

// SeriesStatisticsResource defines model for SeriesStatisticsResource.
type SeriesStatisticsResource struct {
	EpisodeCount      *int32    `json:"episodeCount,omitempty"`
	EpisodeFileCount  *int32    `json:"episodeFileCount,omitempty"`
	PercentOfEpisodes *float64  `json:"percentOfEpisodes,omitempty"`
	ReleaseGroups     *[]string `json:"releaseGroups"`
	SeasonCount       *int32    `json:"seasonCount,omitempty"`
	SizeOnDisk        *int64    `json:"sizeOnDisk,omitempty"`
	TotalEpisodeCount *int32    `json:"totalEpisodeCount,omitempty"`
}

// SeriesStatusType defines model for SeriesStatusType.
type SeriesStatusType string

// SeriesTypes defines model for SeriesTypes.
type SeriesTypes string

// SystemResource defines model for SystemResource.
type SystemResource struct {
	AppData                       *string             `json:"appData"`
	AppName                       *string             `json:"appName"`
	Authentication                *AuthenticationType `json:"authentication,omitempty"`
	Branch                        *string             `json:"branch"`
	BuildTime                     *time.Time          `json:"buildTime,omitempty"`
	DatabaseType                  *DatabaseType       `json:"databaseType,omitempty"`
	DatabaseVersion               *string             `json:"databaseVersion"`
	InstanceName                  *string             `json:"instanceName"`
	IsAdmin                       *bool               `json:"isAdmin,omitempty"`
	IsDebug                       *bool               `json:"isDebug,omitempty"`
	IsDocker                      *bool               `json:"isDocker,omitempty"`
	IsLinux                       *bool               `json:"isLinux,omitempty"`
	IsNetCore                     *bool               `json:"isNetCore,omitempty"`
	IsOsx                         *bool               `json:"isOsx,omitempty"`
	IsProduction                  *bool               `json:"isProduction,omitempty"`
	IsUserInteractive             *bool               `json:"isUserInteractive,omitempty"`
	IsWindows                     *bool               `json:"isWindows,omitempty"`
	MigrationVersion              *int32              `json:"migrationVersion,omitempty"`
	Mode                          *RuntimeMode        `json:"mode,omitempty"`
	OsName                        *string             `json:"osName"`
	OsVersion                     *string             `json:"osVersion"`
	PackageAuthor                 *string             `json:"packageAuthor"`
	PackageUpdateMechanism        *UpdateMechanism    `json:"packageUpdateMechanism,omitempty"`
	PackageUpdateMechanismMessage *string             `json:"packageUpdateMechanismMessage"`
	PackageVersion                *string             `json:"packageVersion"`
	RuntimeName                   *string             `json:"runtimeName"`
	RuntimeVersion                *string             `json:"runtimeVersion"`
	SqliteVersion                 *string             `json:"sqliteVersion"`
	StartTime                     *time.Time          `json:"startTime,omitempty"`
	StartupPath                   *string             `json:"startupPath"`
	UrlBase                       *string             `json:"urlBase"`
	Version                       *string             `json:"version"`
}

// UpdateMechanism defines model for UpdateMechanism.
type UpdateMechanism string

// GetApiV3SeriesParams defines parameters for GetApiV3Series.
type GetApiV3SeriesParams struct {
	TvdbId              *int32 `form:"tvdbId,omitempty" json:"tvdbId,omitempty"`
	IncludeSeasonImages *bool  `form:"includeSeasonImages,omitempty" json:"includeSeasonImages,omitempty"`
}

// PostApiV3CommandJSONRequestBody defines body for PostApiV3Command for application/json ContentType.
type PostApiV3CommandJSONRequestBody = CommandResource

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// PostApiV3CommandWithBody request with any body
	PostApiV3CommandWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostApiV3Command(ctx context.Context, body PostApiV3CommandJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiV3CommandId request
	GetApiV3CommandId(ctx context.Context, id int32, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiV3ConfigHost request
	GetApiV3ConfigHost(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiV3Series request
	GetApiV3Series(ctx context.Context, params *GetApiV3SeriesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiV3SystemBackup request
	GetApiV3SystemBackup(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostApiV3SystemRestart request
	PostApiV3SystemRestart(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiV3SystemStatus request
	GetApiV3SystemStatus(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) PostApiV3CommandWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiV3CommandRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiV3Command(ctx context.Context, body PostApiV3CommandJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiV3CommandRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiV3CommandId(ctx context.Context, id int32, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiV3CommandIdRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiV3ConfigHost(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiV3ConfigHostRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiV3Series(ctx context.Context, params *GetApiV3SeriesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiV3SeriesRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiV3SystemBackup(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiV3SystemBackupRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiV3SystemRestart(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiV3SystemRestartRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiV3SystemStatus(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiV3SystemStatusRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewPostApiV3CommandRequest calls the generic PostApiV3Command builder with application/json body
func NewPostApiV3CommandRequest(server string, body PostApiV3CommandJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostApiV3CommandRequestWithBody(server, "application/json", bodyReader)
}

// NewPostApiV3CommandRequestWithBody generates requests for PostApiV3Command with any type of body
func NewPostApiV3CommandRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v3/command")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetApiV3CommandIdRequest generates requests for GetApiV3CommandId
func NewGetApiV3CommandIdRequest(server string, id int32) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v3/command/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetApiV3ConfigHostRequest generates requests for GetApiV3ConfigHost
func NewGetApiV3ConfigHostRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v3/config/host")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetApiV3SeriesRequest generates requests for GetApiV3Series
func NewGetApiV3SeriesRequest(server string, params *GetApiV3SeriesParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v3/series")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.TvdbId != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "tvdbId", runtime.ParamLocationQuery, *params.TvdbId); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.IncludeSeasonImages != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "includeSeasonImages", runtime.ParamLocationQuery, *params.IncludeSeasonImages); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetApiV3SystemBackupRequest generates requests for GetApiV3SystemBackup
func NewGetApiV3SystemBackupRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v3/system/backup")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostApiV3SystemRestartRequest generates requests for PostApiV3SystemRestart
func NewPostApiV3SystemRestartRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v3/system/restart")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetApiV3SystemStatusRequest generates requests for GetApiV3SystemStatus
func NewGetApiV3SystemStatusRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v3/system/status")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// PostApiV3CommandWithBodyWithResponse request with any body
	PostApiV3CommandWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiV3CommandResponse, error)

	PostApiV3CommandWithResponse(ctx context.Context, body PostApiV3CommandJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiV3CommandResponse, error)

	// GetApiV3CommandIdWithResponse request
	GetApiV3CommandIdWithResponse(ctx context.Context, id int32, reqEditors ...RequestEditorFn) (*GetApiV3CommandIdResponse, error)

	// GetApiV3ConfigHostWithResponse request
	GetApiV3ConfigHostWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiV3ConfigHostResponse, error)

	// GetApiV3SeriesWithResponse request
	GetApiV3SeriesWithResponse(ctx context.Context, params *GetApiV3SeriesParams, reqEditors ...RequestEditorFn) (*GetApiV3SeriesResponse, error)

	// GetApiV3SystemBackupWithResponse request
	GetApiV3SystemBackupWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiV3SystemBackupResponse, error)

	// PostApiV3SystemRestartWithResponse request
	PostApiV3SystemRestartWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*PostApiV3SystemRestartResponse, error)

	// GetApiV3SystemStatusWithResponse request
	GetApiV3SystemStatusWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiV3SystemStatusResponse, error)
}

type PostApiV3CommandResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *CommandResource
}

// Status returns HTTPResponse.Status
func (r PostApiV3CommandResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostApiV3CommandResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetApiV3CommandIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *CommandResource
}

// Status returns HTTPResponse.Status
func (r GetApiV3CommandIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiV3CommandIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetApiV3ConfigHostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *HostConfigResource
}

// Status returns HTTPResponse.Status
func (r GetApiV3ConfigHostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiV3ConfigHostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetApiV3SeriesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]SeriesResource
}

// Status returns HTTPResponse.Status
func (r GetApiV3SeriesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiV3SeriesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetApiV3SystemBackupResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]BackupResource
}

// Status returns HTTPResponse.Status
func (r GetApiV3SystemBackupResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiV3SystemBackupResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostApiV3SystemRestartResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r PostApiV3SystemRestartResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostApiV3SystemRestartResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetApiV3SystemStatusResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *SystemResource
}

// Status returns HTTPResponse.Status
func (r GetApiV3SystemStatusResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiV3SystemStatusResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// PostApiV3CommandWithBodyWithResponse request with arbitrary body returning *PostApiV3CommandResponse
func (c *ClientWithResponses) PostApiV3CommandWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiV3CommandResponse, error) {
	rsp, err := c.PostApiV3CommandWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiV3CommandResponse(rsp)
}

func (c *ClientWithResponses) PostApiV3CommandWithResponse(ctx context.Context, body PostApiV3CommandJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiV3CommandResponse, error) {
	rsp, err := c.PostApiV3Command(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiV3CommandResponse(rsp)
}

// GetApiV3CommandIdWithResponse request returning *GetApiV3CommandIdResponse
func (c *ClientWithResponses) GetApiV3CommandIdWithResponse(ctx context.Context, id int32, reqEditors ...RequestEditorFn) (*GetApiV3CommandIdResponse, error) {
	rsp, err := c.GetApiV3CommandId(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiV3CommandIdResponse(rsp)
}

// GetApiV3ConfigHostWithResponse request returning *GetApiV3ConfigHostResponse
func (c *ClientWithResponses) GetApiV3ConfigHostWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiV3ConfigHostResponse, error) {
	rsp, err := c.GetApiV3ConfigHost(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiV3ConfigHostResponse(rsp)
}

// GetApiV3SeriesWithResponse request returning *GetApiV3SeriesResponse
func (c *ClientWithResponses) GetApiV3SeriesWithResponse(ctx context.Context, params *GetApiV3SeriesParams, reqEditors ...RequestEditorFn) (*GetApiV3SeriesResponse, error) {
	rsp, err := c.GetApiV3Series(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiV3SeriesResponse(rsp)
}

// GetApiV3SystemBackupWithResponse request returning *GetApiV3SystemBackupResponse
func (c *ClientWithResponses) GetApiV3SystemBackupWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiV3SystemBackupResponse, error) {
	rsp, err := c.GetApiV3SystemBackup(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiV3SystemBackupResponse(rsp)
}

// PostApiV3SystemRestartWithResponse request returning *PostApiV3SystemRestartResponse
func (c *ClientWithResponses) PostApiV3SystemRestartWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*PostApiV3SystemRestartResponse, error) {
	rsp, err := c.PostApiV3SystemRestart(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiV3SystemRestartResponse(rsp)
}

// GetApiV3SystemStatusWithResponse request returning *GetApiV3SystemStatusResponse
func (c *ClientWithResponses) GetApiV3SystemStatusWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiV3SystemStatusResponse, error) {
	rsp, err := c.GetApiV3SystemStatus(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiV3SystemStatusResponse(rsp)
}

// ParsePostApiV3CommandResponse parses an HTTP response from a PostApiV3CommandWithResponse call
func ParsePostApiV3CommandResponse(rsp *http.Response) (*PostApiV3CommandResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostApiV3CommandResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CommandResource
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetApiV3CommandIdResponse parses an HTTP response from a GetApiV3CommandIdWithResponse call
func ParseGetApiV3CommandIdResponse(rsp *http.Response) (*GetApiV3CommandIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiV3CommandIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CommandResource
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetApiV3ConfigHostResponse parses an HTTP response from a GetApiV3ConfigHostWithResponse call
func ParseGetApiV3ConfigHostResponse(rsp *http.Response) (*GetApiV3ConfigHostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiV3ConfigHostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest HostConfigResource
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case rsp.StatusCode == 200:
		// Content-type (text/plain) unsupported

	}

	return response, nil
}

// ParseGetApiV3SeriesResponse parses an HTTP response from a GetApiV3SeriesWithResponse call
func ParseGetApiV3SeriesResponse(rsp *http.Response) (*GetApiV3SeriesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiV3SeriesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []SeriesResource
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetApiV3SystemBackupResponse parses an HTTP response from a GetApiV3SystemBackupWithResponse call
func ParseGetApiV3SystemBackupResponse(rsp *http.Response) (*GetApiV3SystemBackupResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiV3SystemBackupResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []BackupResource
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case rsp.StatusCode == 200:
		// Content-type (text/plain) unsupported

	}

	return response, nil
}

// ParsePostApiV3SystemRestartResponse parses an HTTP response from a PostApiV3SystemRestartWithResponse call
func ParsePostApiV3SystemRestartResponse(rsp *http.Response) (*PostApiV3SystemRestartResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostApiV3SystemRestartResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetApiV3SystemStatusResponse parses an HTTP response from a GetApiV3SystemStatusWithResponse call
func ParseGetApiV3SystemStatusResponse(rsp *http.Response) (*GetApiV3SystemStatusResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiV3SystemStatusResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest SystemResource
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
