// Package radarr provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package radarr

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

const (
	X_Api_KeyScopes = "X_Api_Key.Scopes"
	ApikeyScopes    = "apikey.Scopes"
)

// Defines values for AddMovieMethod.
const (
	AddMovieMethodCollection AddMovieMethod = "collection"
	AddMovieMethodList       AddMovieMethod = "list"
	AddMovieMethodManual     AddMovieMethod = "manual"
)

// Defines values for AuthenticationRequiredType.
const (
	AuthenticationRequiredTypeDisabledForLocalAddresses AuthenticationRequiredType = "disabledForLocalAddresses"
	AuthenticationRequiredTypeEnabled                   AuthenticationRequiredType = "enabled"
)

// Defines values for AuthenticationType.
const (
	AuthenticationTypeBasic    AuthenticationType = "basic"
	AuthenticationTypeExternal AuthenticationType = "external"
	AuthenticationTypeForms    AuthenticationType = "forms"
	AuthenticationTypeNone     AuthenticationType = "none"
)

// Defines values for BackupType.
const (
	BackupTypeManual    BackupType = "manual"
	BackupTypeScheduled BackupType = "scheduled"
	BackupTypeUpdate    BackupType = "update"
)

// Defines values for CertificateValidationType.
const (
	CertificateValidationTypeDisabled                  CertificateValidationType = "disabled"
	CertificateValidationTypeDisabledForLocalAddresses CertificateValidationType = "disabledForLocalAddresses"
	CertificateValidationTypeEnabled                   CertificateValidationType = "enabled"
)

// Defines values for CommandPriority.
const (
	CommandPriorityHigh   CommandPriority = "high"
	CommandPriorityLow    CommandPriority = "low"
	CommandPriorityNormal CommandPriority = "normal"
)

// Defines values for CommandResult.
const (
	CommandResultSuccessful   CommandResult = "successful"
	CommandResultUnknown      CommandResult = "unknown"
	CommandResultUnsuccessful CommandResult = "unsuccessful"
)

// Defines values for CommandStatus.
const (
	CommandStatusAborted   CommandStatus = "aborted"
	CommandStatusCancelled CommandStatus = "cancelled"
	CommandStatusCompleted CommandStatus = "completed"
	CommandStatusFailed    CommandStatus = "failed"
	CommandStatusOrphaned  CommandStatus = "orphaned"
	CommandStatusQueued    CommandStatus = "queued"
	CommandStatusStarted   CommandStatus = "started"
)

// Defines values for CommandTrigger.
const (
	Manual      CommandTrigger = "manual"
	Scheduled   CommandTrigger = "scheduled"
	Unspecified CommandTrigger = "unspecified"
)

// Defines values for DatabaseType.
const (
	PostgreSQL DatabaseType = "postgreSQL"
	SqLite     DatabaseType = "sqLite"
)

// Defines values for DownloadProtocol.
const (
	DownloadProtocolTorrent DownloadProtocol = "torrent"
	DownloadProtocolUnknown DownloadProtocol = "unknown"
	DownloadProtocolUsenet  DownloadProtocol = "usenet"
)

// Defines values for ImportListType.
const (
	ImportListTypeAdvanced ImportListType = "advanced"
	ImportListTypeOther    ImportListType = "other"
	ImportListTypePlex     ImportListType = "plex"
	ImportListTypeProgram  ImportListType = "program"
	ImportListTypeSimkl    ImportListType = "simkl"
	ImportListTypeTmdb     ImportListType = "tmdb"
	ImportListTypeTrakt    ImportListType = "trakt"
)

// Defines values for MediaCoverTypes.
const (
	MediaCoverTypesBanner     MediaCoverTypes = "banner"
	MediaCoverTypesClearlogo  MediaCoverTypes = "clearlogo"
	MediaCoverTypesFanart     MediaCoverTypes = "fanart"
	MediaCoverTypesHeadshot   MediaCoverTypes = "headshot"
	MediaCoverTypesPoster     MediaCoverTypes = "poster"
	MediaCoverTypesScreenshot MediaCoverTypes = "screenshot"
	MediaCoverTypesUnknown    MediaCoverTypes = "unknown"
)

// Defines values for Modifier.
const (
	ModifierBrdisk   Modifier = "brdisk"
	ModifierNone     Modifier = "none"
	ModifierRawhd    Modifier = "rawhd"
	ModifierRegional Modifier = "regional"
	ModifierRemux    Modifier = "remux"
	ModifierScreener Modifier = "screener"
)

// Defines values for MonitorTypes.
const (
	MovieAndCollection MonitorTypes = "movieAndCollection"
	MovieOnly          MonitorTypes = "movieOnly"
	None               MonitorTypes = "none"
)

// Defines values for MovieStatusType.
const (
	Announced MovieStatusType = "announced"
	Deleted   MovieStatusType = "deleted"
	InCinemas MovieStatusType = "inCinemas"
	Released  MovieStatusType = "released"
	Tba       MovieStatusType = "tba"
)

// Defines values for PrivacyLevel.
const (
	PrivacyLevelApiKey   PrivacyLevel = "apiKey"
	PrivacyLevelNormal   PrivacyLevel = "normal"
	PrivacyLevelPassword PrivacyLevel = "password"
	PrivacyLevelUserName PrivacyLevel = "userName"
)

// Defines values for ProviderMessageType.
const (
	Error   ProviderMessageType = "error"
	Info    ProviderMessageType = "info"
	Warning ProviderMessageType = "warning"
)

// Defines values for ProxyType.
const (
	Http   ProxyType = "http"
	Socks4 ProxyType = "socks4"
	Socks5 ProxyType = "socks5"
)

// Defines values for QualitySource.
const (
	QualitySourceBluray    QualitySource = "bluray"
	QualitySourceCam       QualitySource = "cam"
	QualitySourceDvd       QualitySource = "dvd"
	QualitySourceTelecine  QualitySource = "telecine"
	QualitySourceTelesync  QualitySource = "telesync"
	QualitySourceTv        QualitySource = "tv"
	QualitySourceUnknown   QualitySource = "unknown"
	QualitySourceWebdl     QualitySource = "webdl"
	QualitySourceWebrip    QualitySource = "webrip"
	QualitySourceWorkprint QualitySource = "workprint"
)

// Defines values for RatingType.
const (
	Critic RatingType = "critic"
	User   RatingType = "user"
)

// Defines values for RuntimeMode.
const (
	Console RuntimeMode = "console"
	Service RuntimeMode = "service"
	Tray    RuntimeMode = "tray"
)

// Defines values for SourceType.
const (
	SourceTypeIndexer  SourceType = "indexer"
	SourceTypeMappings SourceType = "mappings"
	SourceTypeTmdb     SourceType = "tmdb"
	SourceTypeUser     SourceType = "user"
)

// Defines values for UpdateMechanism.
const (
	Apt      UpdateMechanism = "apt"
	BuiltIn  UpdateMechanism = "builtIn"
	Docker   UpdateMechanism = "docker"
	External UpdateMechanism = "external"
	Script   UpdateMechanism = "script"
)

// AddMovieMethod defines model for AddMovieMethod.
type AddMovieMethod string

// AddMovieOptions defines model for AddMovieOptions.
type AddMovieOptions struct {
	AddMethod                  *AddMovieMethod `json:"addMethod,omitempty"`
	IgnoreEpisodesWithFiles    *bool           `json:"ignoreEpisodesWithFiles,omitempty"`
	IgnoreEpisodesWithoutFiles *bool           `json:"ignoreEpisodesWithoutFiles,omitempty"`
	Monitor                    *MonitorTypes   `json:"monitor,omitempty"`
	SearchForMovie             *bool           `json:"searchForMovie,omitempty"`
}

// AlternativeTitleResource defines model for AlternativeTitleResource.
type AlternativeTitleResource struct {
	CleanTitle      *string     `json:"cleanTitle"`
	Id              *int32      `json:"id,omitempty"`
	MovieMetadataId *int32      `json:"movieMetadataId,omitempty"`
	SourceType      *SourceType `json:"sourceType,omitempty"`
	Title           *string     `json:"title"`
}

// AuthenticationRequiredType defines model for AuthenticationRequiredType.
type AuthenticationRequiredType string

// AuthenticationType defines model for AuthenticationType.
type AuthenticationType string

// BackupResource defines model for BackupResource.
type BackupResource struct {
	Id   *int32      `json:"id,omitempty"`
	Name *string     `json:"name"`
	Path *string     `json:"path"`
	Size *int64      `json:"size,omitempty"`
	Time *time.Time  `json:"time,omitempty"`
	Type *BackupType `json:"type,omitempty"`
}

// BackupType defines model for BackupType.
type BackupType string

// CertificateValidationType defines model for CertificateValidationType.
type CertificateValidationType string

// Command defines model for Command.
type Command struct {
	ClientUserAgent     *string         `json:"clientUserAgent"`
	CompletionMessage   *string         `json:"completionMessage"`
	IsExclusive         *bool           `json:"isExclusive,omitempty"`
	IsLongRunning       *bool           `json:"isLongRunning,omitempty"`
	IsTypeExclusive     *bool           `json:"isTypeExclusive,omitempty"`
	LastExecutionTime   *time.Time      `json:"lastExecutionTime"`
	LastStartTime       *time.Time      `json:"lastStartTime"`
	Name                *string         `json:"name"`
	RequiresDiskAccess  *bool           `json:"requiresDiskAccess,omitempty"`
	SendUpdatesToClient *bool           `json:"sendUpdatesToClient,omitempty"`
	SuppressMessages    *bool           `json:"suppressMessages,omitempty"`
	Trigger             *CommandTrigger `json:"trigger,omitempty"`
	UpdateScheduledTask *bool           `json:"updateScheduledTask,omitempty"`
}

// CommandPriority defines model for CommandPriority.
type CommandPriority string

// CommandResource defines model for CommandResource.
type CommandResource struct {
	Body                *Command         `json:"body,omitempty"`
	ClientUserAgent     *string          `json:"clientUserAgent"`
	CommandName         *string          `json:"commandName"`
	Duration            *string          `json:"duration"`
	Ended               *time.Time       `json:"ended"`
	Exception           *string          `json:"exception"`
	Id                  *int32           `json:"id,omitempty"`
	LastExecutionTime   *time.Time       `json:"lastExecutionTime"`
	Message             *string          `json:"message"`
	Name                *string          `json:"name"`
	Priority            *CommandPriority `json:"priority,omitempty"`
	Queued              *time.Time       `json:"queued,omitempty"`
	Result              *CommandResult   `json:"result,omitempty"`
	SendUpdatesToClient *bool            `json:"sendUpdatesToClient,omitempty"`
	Started             *time.Time       `json:"started"`
	StateChangeTime     *time.Time       `json:"stateChangeTime"`
	Status              *CommandStatus   `json:"status,omitempty"`
	Trigger             *CommandTrigger  `json:"trigger,omitempty"`
	UpdateScheduledTask *bool            `json:"updateScheduledTask,omitempty"`
}

// CommandResult defines model for CommandResult.
type CommandResult string

// CommandStatus defines model for CommandStatus.
type CommandStatus string

// CommandTrigger defines model for CommandTrigger.
type CommandTrigger string

// CustomFormatResource defines model for CustomFormatResource.
type CustomFormatResource struct {
	Id                              *int32                             `json:"id,omitempty"`
	IncludeCustomFormatWhenRenaming *bool                              `json:"includeCustomFormatWhenRenaming"`
	Name                            *string                            `json:"name"`
	Specifications                  *[]CustomFormatSpecificationSchema `json:"specifications"`
}

// CustomFormatSpecificationSchema defines model for CustomFormatSpecificationSchema.
type CustomFormatSpecificationSchema struct {
	Fields             *[]Field                           `json:"fields"`
	Id                 *int32                             `json:"id,omitempty"`
	Implementation     *string                            `json:"implementation"`
	ImplementationName *string                            `json:"implementationName"`
	InfoLink           *string                            `json:"infoLink"`
	Name               *string                            `json:"name"`
	Negate             *bool                              `json:"negate,omitempty"`
	Presets            *[]CustomFormatSpecificationSchema `json:"presets"`
	Required           *bool                              `json:"required,omitempty"`
}

// DatabaseType defines model for DatabaseType.
type DatabaseType string

// DownloadClientResource defines model for DownloadClientResource.
type DownloadClientResource struct {
	ConfigContract           *string                   `json:"configContract"`
	Enable                   *bool                     `json:"enable,omitempty"`
	Fields                   *[]Field                  `json:"fields"`
	Id                       *int32                    `json:"id,omitempty"`
	Implementation           *string                   `json:"implementation"`
	ImplementationName       *string                   `json:"implementationName"`
	InfoLink                 *string                   `json:"infoLink"`
	Message                  *ProviderMessage          `json:"message,omitempty"`
	Name                     *string                   `json:"name"`
	Presets                  *[]DownloadClientResource `json:"presets"`
	Priority                 *int32                    `json:"priority,omitempty"`
	Protocol                 *DownloadProtocol         `json:"protocol,omitempty"`
	RemoveCompletedDownloads *bool                     `json:"removeCompletedDownloads,omitempty"`
	RemoveFailedDownloads    *bool                     `json:"removeFailedDownloads,omitempty"`
	Tags                     *[]int32                  `json:"tags"`
}

// DownloadProtocol defines model for DownloadProtocol.
type DownloadProtocol string

// Field defines model for Field.
type Field struct {
	Advanced                    *bool           `json:"advanced,omitempty"`
	HelpLink                    *string         `json:"helpLink"`
	HelpText                    *string         `json:"helpText"`
	HelpTextWarning             *string         `json:"helpTextWarning"`
	Hidden                      *string         `json:"hidden"`
	IsFloat                     *bool           `json:"isFloat,omitempty"`
	Label                       *string         `json:"label"`
	Name                        *string         `json:"name"`
	Order                       *int32          `json:"order,omitempty"`
	Placeholder                 *string         `json:"placeholder"`
	Privacy                     *PrivacyLevel   `json:"privacy,omitempty"`
	Section                     *string         `json:"section"`
	SelectOptions               *[]SelectOption `json:"selectOptions"`
	SelectOptionsProviderAction *string         `json:"selectOptionsProviderAction"`
	Type                        *string         `json:"type"`
	Unit                        *string         `json:"unit"`
	Value                       interface{}     `json:"value"`
}

// HostConfigResource defines model for HostConfigResource.
type HostConfigResource struct {
	AnalyticsEnabled          *bool                       `json:"analyticsEnabled,omitempty"`
	ApiKey                    *string                     `json:"apiKey"`
	ApplicationUrl            *string                     `json:"applicationUrl"`
	AuthenticationMethod      *AuthenticationType         `json:"authenticationMethod,omitempty"`
	AuthenticationRequired    *AuthenticationRequiredType `json:"authenticationRequired,omitempty"`
	BackupFolder              *string                     `json:"backupFolder"`
	BackupInterval            *int32                      `json:"backupInterval,omitempty"`
	BackupRetention           *int32                      `json:"backupRetention,omitempty"`
	BindAddress               *string                     `json:"bindAddress"`
	Branch                    *string                     `json:"branch"`
	CertificateValidation     *CertificateValidationType  `json:"certificateValidation,omitempty"`
	ConsoleLogLevel           *string                     `json:"consoleLogLevel"`
	EnableSsl                 *bool                       `json:"enableSsl,omitempty"`
	Id                        *int32                      `json:"id,omitempty"`
	InstanceName              *string                     `json:"instanceName"`
	LaunchBrowser             *bool                       `json:"launchBrowser,omitempty"`
	LogLevel                  *string                     `json:"logLevel"`
	LogSizeLimit              *int32                      `json:"logSizeLimit,omitempty"`
	Password                  *string                     `json:"password"`
	PasswordConfirmation      *string                     `json:"passwordConfirmation"`
	Port                      *int32                      `json:"port,omitempty"`
	ProxyBypassFilter         *string                     `json:"proxyBypassFilter"`
	ProxyBypassLocalAddresses *bool                       `json:"proxyBypassLocalAddresses,omitempty"`
	ProxyEnabled              *bool                       `json:"proxyEnabled,omitempty"`
	ProxyHostname             *string                     `json:"proxyHostname"`
	ProxyPassword             *string                     `json:"proxyPassword"`
	ProxyPort                 *int32                      `json:"proxyPort,omitempty"`
	ProxyType                 *ProxyType                  `json:"proxyType,omitempty"`
	ProxyUsername             *string                     `json:"proxyUsername"`
	SslCertPassword           *string                     `json:"sslCertPassword"`
	SslCertPath               *string                     `json:"sslCertPath"`
	SslPort                   *int32                      `json:"sslPort,omitempty"`
	TrustCgnatIpAddresses     *bool                       `json:"trustCgnatIpAddresses,omitempty"`
	UpdateAutomatically       *bool                       `json:"updateAutomatically,omitempty"`
	UpdateMechanism           *UpdateMechanism            `json:"updateMechanism,omitempty"`
	UpdateScriptPath          *string                     `json:"updateScriptPath"`
	UrlBase                   *string                     `json:"urlBase"`
	Username                  *string                     `json:"username"`
}

// ImportListExclusionResource defines model for ImportListExclusionResource.
type ImportListExclusionResource struct {
	ConfigContract     *string                        `json:"configContract"`
	Fields             *[]Field                       `json:"fields"`
	Id                 *int32                         `json:"id,omitempty"`
	Implementation     *string                        `json:"implementation"`
	ImplementationName *string                        `json:"implementationName"`
	InfoLink           *string                        `json:"infoLink"`
	Message            *ProviderMessage               `json:"message,omitempty"`
	MovieTitle         *string                        `json:"movieTitle"`
	MovieYear          *int32                         `json:"movieYear,omitempty"`
	Name               *string                        `json:"name"`
	Presets            *[]ImportListExclusionResource `json:"presets"`
	Tags               *[]int32                       `json:"tags"`
	TmdbId             *int32                         `json:"tmdbId,omitempty"`
}

// ImportListResource defines model for ImportListResource.
type ImportListResource struct {
	ConfigContract      *string               `json:"configContract"`
	EnableAuto          *bool                 `json:"enableAuto,omitempty"`
	Enabled             *bool                 `json:"enabled,omitempty"`
	Fields              *[]Field              `json:"fields"`
	Id                  *int32                `json:"id,omitempty"`
	Implementation      *string               `json:"implementation"`
	ImplementationName  *string               `json:"implementationName"`
	InfoLink            *string               `json:"infoLink"`
	ListOrder           *int32                `json:"listOrder,omitempty"`
	ListType            *ImportListType       `json:"listType,omitempty"`
	Message             *ProviderMessage      `json:"message,omitempty"`
	MinRefreshInterval  *string               `json:"minRefreshInterval,omitempty"`
	MinimumAvailability *MovieStatusType      `json:"minimumAvailability,omitempty"`
	Monitor             *MonitorTypes         `json:"monitor,omitempty"`
	Name                *string               `json:"name"`
	Presets             *[]ImportListResource `json:"presets"`
	QualityProfileId    *int32                `json:"qualityProfileId,omitempty"`
	RootFolderPath      *string               `json:"rootFolderPath"`
	SearchOnAdd         *bool                 `json:"searchOnAdd,omitempty"`
	Tags                *[]int32              `json:"tags"`
}

// ImportListType defines model for ImportListType.
type ImportListType string

// IndexerResource defines model for IndexerResource.
type IndexerResource struct {
	ConfigContract          *string            `json:"configContract"`
	DownloadClientId        *int32             `json:"downloadClientId,omitempty"`
	EnableAutomaticSearch   *bool              `json:"enableAutomaticSearch,omitempty"`
	EnableInteractiveSearch *bool              `json:"enableInteractiveSearch,omitempty"`
	EnableRss               *bool              `json:"enableRss,omitempty"`
	Fields                  *[]Field           `json:"fields"`
	Id                      *int32             `json:"id,omitempty"`
	Implementation          *string            `json:"implementation"`
	ImplementationName      *string            `json:"implementationName"`
	InfoLink                *string            `json:"infoLink"`
	Message                 *ProviderMessage   `json:"message,omitempty"`
	Name                    *string            `json:"name"`
	Presets                 *[]IndexerResource `json:"presets"`
	Priority                *int32             `json:"priority,omitempty"`
	Protocol                *DownloadProtocol  `json:"protocol,omitempty"`
	SupportsRss             *bool              `json:"supportsRss,omitempty"`
	SupportsSearch          *bool              `json:"supportsSearch,omitempty"`
	Tags                    *[]int32           `json:"tags"`
}

// Language defines model for Language.
type Language struct {
	Id   *int32  `json:"id,omitempty"`
	Name *string `json:"name"`
}

// MediaCover defines model for MediaCover.
type MediaCover struct {
	CoverType *MediaCoverTypes `json:"coverType,omitempty"`
	RemoteUrl *string          `json:"remoteUrl"`
	Url       *string          `json:"url"`
}

// MediaCoverTypes defines model for MediaCoverTypes.
type MediaCoverTypes string

// MediaInfoResource defines model for MediaInfoResource.
type MediaInfoResource struct {
	AudioBitrate          *int64   `json:"audioBitrate,omitempty"`
	AudioChannels         *float64 `json:"audioChannels,omitempty"`
	AudioCodec            *string  `json:"audioCodec"`
	AudioLanguages        *string  `json:"audioLanguages"`
	AudioStreamCount      *int32   `json:"audioStreamCount,omitempty"`
	Id                    *int32   `json:"id,omitempty"`
	Resolution            *string  `json:"resolution"`
	RunTime               *string  `json:"runTime"`
	ScanType              *string  `json:"scanType"`
	Subtitles             *string  `json:"subtitles"`
	VideoBitDepth         *int32   `json:"videoBitDepth,omitempty"`
	VideoBitrate          *int64   `json:"videoBitrate,omitempty"`
	VideoCodec            *string  `json:"videoCodec"`
	VideoDynamicRange     *string  `json:"videoDynamicRange"`
	VideoDynamicRangeType *string  `json:"videoDynamicRangeType"`
	VideoFps              *float64 `json:"videoFps,omitempty"`
}

// MetadataResource defines model for MetadataResource.
type MetadataResource struct {
	ConfigContract     *string             `json:"configContract"`
	Enable             *bool               `json:"enable,omitempty"`
	Fields             *[]Field            `json:"fields"`
	Id                 *int32              `json:"id,omitempty"`
	Implementation     *string             `json:"implementation"`
	ImplementationName *string             `json:"implementationName"`
	InfoLink           *string             `json:"infoLink"`
	Message            *ProviderMessage    `json:"message,omitempty"`
	Name               *string             `json:"name"`
	Presets            *[]MetadataResource `json:"presets"`
	Tags               *[]int32            `json:"tags"`
}

// Modifier defines model for Modifier.
type Modifier string

// MonitorTypes defines model for MonitorTypes.
type MonitorTypes string

// MovieCollectionResource defines model for MovieCollectionResource.
type MovieCollectionResource struct {
	Title  *string `json:"title"`
	TmdbId *int32  `json:"tmdbId,omitempty"`
}

// MovieFileResource defines model for MovieFileResource.
type MovieFileResource struct {
	CustomFormatScore   *int32                  `json:"customFormatScore"`
	CustomFormats       *[]CustomFormatResource `json:"customFormats"`
	DateAdded           *time.Time              `json:"dateAdded,omitempty"`
	Edition             *string                 `json:"edition"`
	Id                  *int32                  `json:"id,omitempty"`
	IndexerFlags        *int32                  `json:"indexerFlags"`
	Languages           *[]Language             `json:"languages"`
	MediaInfo           *MediaInfoResource      `json:"mediaInfo,omitempty"`
	MovieId             *int32                  `json:"movieId,omitempty"`
	OriginalFilePath    *string                 `json:"originalFilePath"`
	Path                *string                 `json:"path"`
	Quality             *QualityModel           `json:"quality,omitempty"`
	QualityCutoffNotMet *bool                   `json:"qualityCutoffNotMet,omitempty"`
	RelativePath        *string                 `json:"relativePath"`
	ReleaseGroup        *string                 `json:"releaseGroup"`
	SceneName           *string                 `json:"sceneName"`
	Size                *int64                  `json:"size,omitempty"`
}

// MovieResource defines model for MovieResource.
type MovieResource struct {
	AddOptions            *AddMovieOptions            `json:"addOptions,omitempty"`
	Added                 *time.Time                  `json:"added,omitempty"`
	AlternateTitles       *[]AlternativeTitleResource `json:"alternateTitles"`
	Certification         *string                     `json:"certification"`
	CleanTitle            *string                     `json:"cleanTitle"`
	Collection            *MovieCollectionResource    `json:"collection,omitempty"`
	DigitalRelease        *time.Time                  `json:"digitalRelease"`
	Folder                *string                     `json:"folder"`
	FolderName            *string                     `json:"folderName"`
	Genres                *[]string                   `json:"genres"`
	HasFile               *bool                       `json:"hasFile"`
	Id                    *int32                      `json:"id,omitempty"`
	Images                *[]MediaCover               `json:"images"`
	ImdbId                *string                     `json:"imdbId"`
	InCinemas             *time.Time                  `json:"inCinemas"`
	IsAvailable           *bool                       `json:"isAvailable,omitempty"`
	Keywords              *[]string                   `json:"keywords"`
	LastSearchTime        *time.Time                  `json:"lastSearchTime"`
	MinimumAvailability   *MovieStatusType            `json:"minimumAvailability,omitempty"`
	Monitored             *bool                       `json:"monitored,omitempty"`
	MovieFile             *MovieFileResource          `json:"movieFile,omitempty"`
	MovieFileId           *int32                      `json:"movieFileId,omitempty"`
	OriginalLanguage      *Language                   `json:"originalLanguage,omitempty"`
	OriginalTitle         *string                     `json:"originalTitle"`
	Overview              *string                     `json:"overview"`
	Path                  *string                     `json:"path"`
	PhysicalRelease       *time.Time                  `json:"physicalRelease"`
	PhysicalReleaseNote   *string                     `json:"physicalReleaseNote"`
	Popularity            *float32                    `json:"popularity,omitempty"`
	QualityProfileId      *int32                      `json:"qualityProfileId,omitempty"`
	Ratings               *Ratings                    `json:"ratings,omitempty"`
	ReleaseDate           *time.Time                  `json:"releaseDate"`
	RemotePoster          *string                     `json:"remotePoster"`
	RootFolderPath        *string                     `json:"rootFolderPath"`
	Runtime               *int32                      `json:"runtime,omitempty"`
	SecondaryYear         *int32                      `json:"secondaryYear"`
	SecondaryYearSourceId *int32                      `json:"secondaryYearSourceId,omitempty"`
	SizeOnDisk            *int64                      `json:"sizeOnDisk"`
	SortTitle             *string                     `json:"sortTitle"`
	Statistics            *MovieStatisticsResource    `json:"statistics,omitempty"`
	Status                *MovieStatusType            `json:"status,omitempty"`
	Studio                *string                     `json:"studio"`
	Tags                  *[]int32                    `json:"tags"`
	Title                 *string                     `json:"title"`
	TitleSlug             *string                     `json:"titleSlug"`
	TmdbId                *int32                      `json:"tmdbId,omitempty"`
	Website               *string                     `json:"website"`
	Year                  *int32                      `json:"year,omitempty"`
	YouTubeTrailerId      *string                     `json:"youTubeTrailerId"`
}

// MovieStatisticsResource defines model for MovieStatisticsResource.
type MovieStatisticsResource struct {
	MovieFileCount *int32    `json:"movieFileCount,omitempty"`
	ReleaseGroups  *[]string `json:"releaseGroups"`
	SizeOnDisk     *int64    `json:"sizeOnDisk,omitempty"`
}

// MovieStatusType defines model for MovieStatusType.
type MovieStatusType string

// NotificationResource defines model for NotificationResource.
type NotificationResource struct {
	ConfigContract                      *string                 `json:"configContract"`
	Fields                              *[]Field                `json:"fields"`
	Id                                  *int32                  `json:"id,omitempty"`
	Implementation                      *string                 `json:"implementation"`
	ImplementationName                  *string                 `json:"implementationName"`
	IncludeHealthWarnings               *bool                   `json:"includeHealthWarnings,omitempty"`
	InfoLink                            *string                 `json:"infoLink"`
	Link                                *string                 `json:"link"`
	Message                             *ProviderMessage        `json:"message,omitempty"`
	Name                                *string                 `json:"name"`
	OnApplicationUpdate                 *bool                   `json:"onApplicationUpdate,omitempty"`
	OnDownload                          *bool                   `json:"onDownload,omitempty"`
	OnGrab                              *bool                   `json:"onGrab,omitempty"`
	OnHealthIssue                       *bool                   `json:"onHealthIssue,omitempty"`
	OnHealthRestored                    *bool                   `json:"onHealthRestored,omitempty"`
	OnManualInteractionRequired         *bool                   `json:"onManualInteractionRequired,omitempty"`
	OnMovieAdded                        *bool                   `json:"onMovieAdded,omitempty"`
	OnMovieDelete                       *bool                   `json:"onMovieDelete,omitempty"`
	OnMovieFileDelete                   *bool                   `json:"onMovieFileDelete,omitempty"`
	OnMovieFileDeleteForUpgrade         *bool                   `json:"onMovieFileDeleteForUpgrade,omitempty"`
	OnRename                            *bool                   `json:"onRename,omitempty"`
	OnUpgrade                           *bool                   `json:"onUpgrade,omitempty"`
	Presets                             *[]NotificationResource `json:"presets"`
	SupportsOnApplicationUpdate         *bool                   `json:"supportsOnApplicationUpdate,omitempty"`
	SupportsOnDownload                  *bool                   `json:"supportsOnDownload,omitempty"`
	SupportsOnGrab                      *bool                   `json:"supportsOnGrab,omitempty"`
	SupportsOnHealthIssue               *bool                   `json:"supportsOnHealthIssue,omitempty"`
	SupportsOnHealthRestored            *bool                   `json:"supportsOnHealthRestored,omitempty"`
	SupportsOnManualInteractionRequired *bool                   `json:"supportsOnManualInteractionRequired,omitempty"`
	SupportsOnMovieAdded                *bool                   `json:"supportsOnMovieAdded,omitempty"`
	SupportsOnMovieDelete               *bool                   `json:"supportsOnMovieDelete,omitempty"`
	SupportsOnMovieFileDelete           *bool                   `json:"supportsOnMovieFileDelete,omitempty"`
	SupportsOnMovieFileDeleteForUpgrade *bool                   `json:"supportsOnMovieFileDeleteForUpgrade,omitempty"`
	SupportsOnRename                    *bool                   `json:"supportsOnRename,omitempty"`
	SupportsOnUpgrade                   *bool                   `json:"supportsOnUpgrade,omitempty"`
	Tags                                *[]int32                `json:"tags"`
	TestCommand                         *string                 `json:"testCommand"`
}

// PrivacyLevel defines model for PrivacyLevel.
type PrivacyLevel string

// ProviderMessage defines model for ProviderMessage.
type ProviderMessage struct {
	Message *string              `json:"message"`
	Type    *ProviderMessageType `json:"type,omitempty"`
}

// ProviderMessageType defines model for ProviderMessageType.
type ProviderMessageType string

// ProxyType defines model for ProxyType.
type ProxyType string

// Quality defines model for Quality.
type Quality struct {
	Id         *int32         `json:"id,omitempty"`
	Modifier   *Modifier      `json:"modifier,omitempty"`
	Name       *string        `json:"name"`
	Resolution *int32         `json:"resolution,omitempty"`
	Source     *QualitySource `json:"source,omitempty"`
}

// QualityModel defines model for QualityModel.
type QualityModel struct {
	Quality  *Quality  `json:"quality,omitempty"`
	Revision *Revision `json:"revision,omitempty"`
}

// QualityProfileQualityItemResource defines model for QualityProfileQualityItemResource.
type QualityProfileQualityItemResource struct {
	Allowed *bool                                `json:"allowed,omitempty"`
	Id      *int32                               `json:"id,omitempty"`
	Items   *[]QualityProfileQualityItemResource `json:"items"`
	Name    *string                              `json:"name"`
	Quality *Quality                             `json:"quality,omitempty"`
}

// QualitySource defines model for QualitySource.
type QualitySource string

// RatingChild defines model for RatingChild.
type RatingChild struct {
	Type  *RatingType `json:"type,omitempty"`
	Value *float64    `json:"value,omitempty"`
	Votes *int32      `json:"votes,omitempty"`
}

// RatingType defines model for RatingType.
type RatingType string

// Ratings defines model for Ratings.
type Ratings struct {
	Imdb           *RatingChild `json:"imdb,omitempty"`
	Metacritic     *RatingChild `json:"metacritic,omitempty"`
	RottenTomatoes *RatingChild `json:"rottenTomatoes,omitempty"`
	Tmdb           *RatingChild `json:"tmdb,omitempty"`
	Trakt          *RatingChild `json:"trakt,omitempty"`
}

// Revision defines model for Revision.
type Revision struct {
	IsRepack *bool  `json:"isRepack,omitempty"`
	Real     *int32 `json:"real,omitempty"`
	Version  *int32 `json:"version,omitempty"`
}

// RuntimeMode defines model for RuntimeMode.
type RuntimeMode string

// SelectOption defines model for SelectOption.
type SelectOption struct {
	DividerAfter *bool   `json:"dividerAfter,omitempty"`
	Hint         *string `json:"hint"`
	Name         *string `json:"name"`
	Order        *int32  `json:"order,omitempty"`
	Value        *int32  `json:"value,omitempty"`
}

// SourceType defines model for SourceType.
type SourceType string

// SystemResource defines model for SystemResource.
type SystemResource struct {
	AppData                       *string             `json:"appData"`
	AppName                       *string             `json:"appName"`
	Authentication                *AuthenticationType `json:"authentication,omitempty"`
	Branch                        *string             `json:"branch"`
	BuildTime                     *time.Time          `json:"buildTime,omitempty"`
	DatabaseType                  *DatabaseType       `json:"databaseType,omitempty"`
	DatabaseVersion               *string             `json:"databaseVersion"`
	InstanceName                  *string             `json:"instanceName"`
	IsAdmin                       *bool               `json:"isAdmin,omitempty"`
	IsDebug                       *bool               `json:"isDebug,omitempty"`
	IsDocker                      *bool               `json:"isDocker,omitempty"`
	IsLinux                       *bool               `json:"isLinux,omitempty"`
	IsNetCore                     *bool               `json:"isNetCore,omitempty"`
	IsOsx                         *bool               `json:"isOsx,omitempty"`
	IsProduction                  *bool               `json:"isProduction,omitempty"`
	IsUserInteractive             *bool               `json:"isUserInteractive,omitempty"`
	IsWindows                     *bool               `json:"isWindows,omitempty"`
	MigrationVersion              *int32              `json:"migrationVersion,omitempty"`
	Mode                          *RuntimeMode        `json:"mode,omitempty"`
	OsName                        *string             `json:"osName"`
	OsVersion                     *string             `json:"osVersion"`
	PackageAuthor                 *string             `json:"packageAuthor"`
	PackageUpdateMechanism        *UpdateMechanism    `json:"packageUpdateMechanism,omitempty"`
	PackageUpdateMechanismMessage *string             `json:"packageUpdateMechanismMessage"`
	PackageVersion                *string             `json:"packageVersion"`
	RuntimeName                   *string             `json:"runtimeName"`
	RuntimeVersion                *string             `json:"runtimeVersion"`
	StartTime                     *time.Time          `json:"startTime,omitempty"`
	StartupPath                   *string             `json:"startupPath"`
	UrlBase                       *string             `json:"urlBase"`
	Version                       *string             `json:"version"`
}

// UpdateMechanism defines model for UpdateMechanism.
type UpdateMechanism string

// GetApiV3MovieParams defines parameters for GetApiV3Movie.
type GetApiV3MovieParams struct {
	TmdbId             *int32 `form:"tmdbId,omitempty" json:"tmdbId,omitempty"`
	ExcludeLocalCovers *bool  `form:"excludeLocalCovers,omitempty" json:"excludeLocalCovers,omitempty"`
	LanguageId         *int32 `form:"languageId,omitempty" json:"languageId,omitempty"`
}

// PostApiV3CommandJSONRequestBody defines body for PostApiV3Command for application/json ContentType.
type PostApiV3CommandJSONRequestBody = CommandResource

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// PostApiV3CommandWithBody request with any body
	PostApiV3CommandWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostApiV3Command(ctx context.Context, body PostApiV3CommandJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiV3CommandId request
	GetApiV3CommandId(ctx context.Context, id int32, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiV3ConfigHost request
	GetApiV3ConfigHost(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiV3Movie request
	GetApiV3Movie(ctx context.Context, params *GetApiV3MovieParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiV3SystemBackup request
	GetApiV3SystemBackup(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostApiV3SystemRestart request
	PostApiV3SystemRestart(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiV3SystemStatus request
	GetApiV3SystemStatus(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) PostApiV3CommandWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiV3CommandRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiV3Command(ctx context.Context, body PostApiV3CommandJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiV3CommandRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiV3CommandId(ctx context.Context, id int32, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiV3CommandIdRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiV3ConfigHost(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiV3ConfigHostRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiV3Movie(ctx context.Context, params *GetApiV3MovieParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiV3MovieRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiV3SystemBackup(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiV3SystemBackupRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiV3SystemRestart(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiV3SystemRestartRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiV3SystemStatus(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiV3SystemStatusRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewPostApiV3CommandRequest calls the generic PostApiV3Command builder with application/json body
func NewPostApiV3CommandRequest(server string, body PostApiV3CommandJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostApiV3CommandRequestWithBody(server, "application/json", bodyReader)
}

// NewPostApiV3CommandRequestWithBody generates requests for PostApiV3Command with any type of body
func NewPostApiV3CommandRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v3/command")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetApiV3CommandIdRequest generates requests for GetApiV3CommandId
func NewGetApiV3CommandIdRequest(server string, id int32) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v3/command/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetApiV3ConfigHostRequest generates requests for GetApiV3ConfigHost
func NewGetApiV3ConfigHostRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v3/config/host")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetApiV3MovieRequest generates requests for GetApiV3Movie
func NewGetApiV3MovieRequest(server string, params *GetApiV3MovieParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v3/movie")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.TmdbId != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "tmdbId", runtime.ParamLocationQuery, *params.TmdbId); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.ExcludeLocalCovers != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "excludeLocalCovers", runtime.ParamLocationQuery, *params.ExcludeLocalCovers); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.LanguageId != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "languageId", runtime.ParamLocationQuery, *params.LanguageId); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetApiV3SystemBackupRequest generates requests for GetApiV3SystemBackup
func NewGetApiV3SystemBackupRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v3/system/backup")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostApiV3SystemRestartRequest generates requests for PostApiV3SystemRestart
func NewPostApiV3SystemRestartRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v3/system/restart")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetApiV3SystemStatusRequest generates requests for GetApiV3SystemStatus
func NewGetApiV3SystemStatusRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v3/system/status")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// PostApiV3CommandWithBodyWithResponse request with any body
	PostApiV3CommandWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiV3CommandResponse, error)

	PostApiV3CommandWithResponse(ctx context.Context, body PostApiV3CommandJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiV3CommandResponse, error)

	// GetApiV3CommandIdWithResponse request
	GetApiV3CommandIdWithResponse(ctx context.Context, id int32, reqEditors ...RequestEditorFn) (*GetApiV3CommandIdResponse, error)

	// GetApiV3ConfigHostWithResponse request
	GetApiV3ConfigHostWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiV3ConfigHostResponse, error)

	// GetApiV3MovieWithResponse request
	GetApiV3MovieWithResponse(ctx context.Context, params *GetApiV3MovieParams, reqEditors ...RequestEditorFn) (*GetApiV3MovieResponse, error)

	// GetApiV3SystemBackupWithResponse request
	GetApiV3SystemBackupWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiV3SystemBackupResponse, error)

	// PostApiV3SystemRestartWithResponse request
	PostApiV3SystemRestartWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*PostApiV3SystemRestartResponse, error)

	// GetApiV3SystemStatusWithResponse request
	GetApiV3SystemStatusWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiV3SystemStatusResponse, error)
}

type PostApiV3CommandResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *CommandResource
}

// Status returns HTTPResponse.Status
func (r PostApiV3CommandResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostApiV3CommandResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetApiV3CommandIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *CommandResource
}

// Status returns HTTPResponse.Status
func (r GetApiV3CommandIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiV3CommandIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetApiV3ConfigHostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *HostConfigResource
}

// Status returns HTTPResponse.Status
func (r GetApiV3ConfigHostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiV3ConfigHostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetApiV3MovieResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]MovieResource
}

// Status returns HTTPResponse.Status
func (r GetApiV3MovieResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiV3MovieResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetApiV3SystemBackupResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]BackupResource
}

// Status returns HTTPResponse.Status
func (r GetApiV3SystemBackupResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiV3SystemBackupResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostApiV3SystemRestartResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r PostApiV3SystemRestartResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostApiV3SystemRestartResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetApiV3SystemStatusResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *SystemResource
}

// Status returns HTTPResponse.Status
func (r GetApiV3SystemStatusResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiV3SystemStatusResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// PostApiV3CommandWithBodyWithResponse request with arbitrary body returning *PostApiV3CommandResponse
func (c *ClientWithResponses) PostApiV3CommandWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiV3CommandResponse, error) {
	rsp, err := c.PostApiV3CommandWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiV3CommandResponse(rsp)
}

func (c *ClientWithResponses) PostApiV3CommandWithResponse(ctx context.Context, body PostApiV3CommandJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiV3CommandResponse, error) {
	rsp, err := c.PostApiV3Command(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiV3CommandResponse(rsp)
}

// GetApiV3CommandIdWithResponse request returning *GetApiV3CommandIdResponse
func (c *ClientWithResponses) GetApiV3CommandIdWithResponse(ctx context.Context, id int32, reqEditors ...RequestEditorFn) (*GetApiV3CommandIdResponse, error) {
	rsp, err := c.GetApiV3CommandId(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiV3CommandIdResponse(rsp)
}

// GetApiV3ConfigHostWithResponse request returning *GetApiV3ConfigHostResponse
func (c *ClientWithResponses) GetApiV3ConfigHostWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiV3ConfigHostResponse, error) {
	rsp, err := c.GetApiV3ConfigHost(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiV3ConfigHostResponse(rsp)
}

// GetApiV3MovieWithResponse request returning *GetApiV3MovieResponse
func (c *ClientWithResponses) GetApiV3MovieWithResponse(ctx context.Context, params *GetApiV3MovieParams, reqEditors ...RequestEditorFn) (*GetApiV3MovieResponse, error) {
	rsp, err := c.GetApiV3Movie(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiV3MovieResponse(rsp)
}

// GetApiV3SystemBackupWithResponse request returning *GetApiV3SystemBackupResponse
func (c *ClientWithResponses) GetApiV3SystemBackupWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiV3SystemBackupResponse, error) {
	rsp, err := c.GetApiV3SystemBackup(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiV3SystemBackupResponse(rsp)
}

// PostApiV3SystemRestartWithResponse request returning *PostApiV3SystemRestartResponse
func (c *ClientWithResponses) PostApiV3SystemRestartWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*PostApiV3SystemRestartResponse, error) {
	rsp, err := c.PostApiV3SystemRestart(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiV3SystemRestartResponse(rsp)
}

// GetApiV3SystemStatusWithResponse request returning *GetApiV3SystemStatusResponse
func (c *ClientWithResponses) GetApiV3SystemStatusWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiV3SystemStatusResponse, error) {
	rsp, err := c.GetApiV3SystemStatus(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiV3SystemStatusResponse(rsp)
}

// ParsePostApiV3CommandResponse parses an HTTP response from a PostApiV3CommandWithResponse call
func ParsePostApiV3CommandResponse(rsp *http.Response) (*PostApiV3CommandResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostApiV3CommandResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CommandResource
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetApiV3CommandIdResponse parses an HTTP response from a GetApiV3CommandIdWithResponse call
func ParseGetApiV3CommandIdResponse(rsp *http.Response) (*GetApiV3CommandIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiV3CommandIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CommandResource
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case rsp.StatusCode == 200:
		// Content-type (text/plain) unsupported

	}

	return response, nil
}

// ParseGetApiV3ConfigHostResponse parses an HTTP response from a GetApiV3ConfigHostWithResponse call
func ParseGetApiV3ConfigHostResponse(rsp *http.Response) (*GetApiV3ConfigHostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiV3ConfigHostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest HostConfigResource
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case rsp.StatusCode == 200:
		// Content-type (text/plain) unsupported

	}

	return response, nil
}

// ParseGetApiV3MovieResponse parses an HTTP response from a GetApiV3MovieWithResponse call
func ParseGetApiV3MovieResponse(rsp *http.Response) (*GetApiV3MovieResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiV3MovieResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []MovieResource
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case rsp.StatusCode == 200:
		// Content-type (text/plain) unsupported

	}

	return response, nil
}

// ParseGetApiV3SystemBackupResponse parses an HTTP response from a GetApiV3SystemBackupWithResponse call
func ParseGetApiV3SystemBackupResponse(rsp *http.Response) (*GetApiV3SystemBackupResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiV3SystemBackupResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []BackupResource
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case rsp.StatusCode == 200:
		// Content-type (text/plain) unsupported

	}

	return response, nil
}

// ParsePostApiV3SystemRestartResponse parses an HTTP response from a PostApiV3SystemRestartWithResponse call
func ParsePostApiV3SystemRestartResponse(rsp *http.Response) (*PostApiV3SystemRestartResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostApiV3SystemRestartResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetApiV3SystemStatusResponse parses an HTTP response from a GetApiV3SystemStatusWithResponse call
func ParseGetApiV3SystemStatusResponse(rsp *http.Response) (*GetApiV3SystemStatusResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiV3SystemStatusResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest SystemResource
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case rsp.StatusCode == 200:
		// Content-type (text/plain) unsupported

	}

	return response, nil
}
